counterfactual/monorepo

packages/apps/contracts/CommitRevealApp.sol
packages/apps/contracts/CountingApp.sol
packages/apps/contracts/Nim.sol
packages/contracts/contracts/StateChannel.sol

This PR marks all `applyAction` functions in sample apps as pure (instead of view) and also marks `computeActionHash` as pure

mark some functions as pure

---

.gitignore

with the previous gitignore, any directory called `lib` was ignored

only exclude root-level lib

---

contracts/NonceRegistry.sol

This PR renames the `nonce` parameter in `NonceRegistry::isFinalized` to be more specific.

rename nonce -> expectedNonce in isFinalized

---

contracts/NonceRegistry.sol
test/integration/commitReveal.spec.ts
test/unit/nonceRegistry.spec.ts
utils/stateChannel.ts

This PR allows the nonce registry to support custom timeouts by making the timeout parameter part of the key. This allows allows us to remove the `finalizeNonce` function (you can simply set a nonce with timeout 0).
This PR also fixes a bug where it was possible to reset a nonce after the timeout, and adds some documentation.
This PR also does not extend the timeout if a nonce has already been set before.
NB: @emansipater has described an alternative design that stores the last two finalization times in the nonce, and allows dependents to specify their own timeout.

support custom timeout in nonceRegistry

---

contracts/lib/Transfer.sol

IMO `terms.limit` being an upper bound is better. The current behaviour is
1. if `details > limit`, fail
1. if `details < limit`, fail
this new behaviour removes case (2), which makes sense to me

make terms.limit an upper bound

---

README.md

This PR replaces an old link to the file `ARCHITECTURE.md` with a link to the new home of the file

link to specs repo

---

packages/contracts/contracts/AppInstance.sol

Before this PR, an open channel would return a default resolution (one where all fields was 0).

Enforce `onlyWhenChannelClosed` modifier on `getResolution`

---

packages/contracts/test/integration/commitReveal.spec.ts

This PR makes commitReveal.spec.ts use the same import and setupTestEnv conventions as the other tests

normalize commitReveal.spec.ts a bit

---

packages/cf.js/src/client.ts

Instead of doing a `.forEach` for every observer to lookup an observerID by its callback, we can do a while-block using `.entries()` and stop as soon as we find what we're looking for.

[cf.js] Adds stoppable iteration for Client.removeObserver()

---

packages/cf.js/package.json
packages/cf.js/src/client.ts
yarn.lock

`Math.random()` isn't collision-safe to use its values as request IDs. Inspired on HTTP request IDs, this PR replaces the random value ID with a UUID-v1-compliant value, linked to a timestamp. Eventually, should there be any logging operations for debugging purposes, a UUID-v1 is timestamp-based, so requests occured within a small time period will have "near" request IDs.

[cf.js] Implements Cf.requestId() with UUID

---

packages/cf.js/rollup.config.js
packages/cf.js/src/legacy/client.ts
packages/iframe-wallet-poc/iframe-wallet/index.html

Currently, the iframe wallet is breaking for a few reasons. To get it working again, we needed to rename the cf.js rollup build to `cf`, which the other packages are expecting as a global. We need to load it before the other packages as well, as they depend on it. And we also have to temporarily remove its dependency on `uuid`, unless we can find a way to inject it as a global.

[cf.js][wallet] get the iife build working correctly again

---

packages/machine/package.json

Without this, errors thrown outside a catch block mostly don't print stack traces.
how to pass arguments to node: https://github.com/facebook/create-react-app/issues/549

pass --trace-warnings flag to node on test

---

packages/iframe-wallet-poc/src/commitmentStore.ts
packages/iframe-wallet-poc/src/iframe/ioProvider.ts
packages/iframe-wallet-poc/src/iframe/user.ts
packages/machine/src/action.ts
packages/machine/src/instruction-executor.ts
packages/machine/src/middleware/middleware.ts
packages/machine/src/middleware/protocol-operation/op-generator.ts
packages/machine/src/middleware/state-transition/install-proposer.ts
packages/machine/src/middleware/state-transition/state-transition.ts
packages/machine/src/write-ahead-log.ts
packages/machine/test/integration/resume-protocols.spec.ts
packages/machine/test/integration/test-commitment-store.ts
packages/machine/test/integration/test-io-provider.ts
packages/machine/test/integration/test-response-sink.ts
packages/machine/test/integration/test-setup.ts
packages/machine/test/unit/write-ahead-log.spec.ts

- delete `context.results` 
- delete `get{First, Last}result`
- creates a `context.intermediateResults` that holds what used to be stored in `context.results`
- middlewares now mutate `context.intermediateResults` directly
- merges `Action` and `ActionExecution`
- fixes #131, #115

[machine] replace `Context::results` array by an explicitly keyed `intermediateResults` object

---

README.md

`iframe-wallet-poc` package was removed. This removes the reference to it in the README
Caused by #245

[monorepo] Remove reference to iframe-wallet-poc

---

packages/cf.js/API_REFERENCE.md
packages/cf.js/src/app-instance.ts
packages/cf.js/src/simple-types.ts

@ebryn and co. pointed out that it makes more sense that the identifier of an app instance is called "AppInstanceID" as opposed to "AppID". "AppID" better describes the identifier on an app *definition*.

Rename AppId -> AppInstanceId

---

packages/cf.js/API_REFERENCE.md

Update the CFjs spec after a productive call with @ebryn, @joelalejandro, @patience-tema-baron.
1) Add all event listeners to top-level Provider. Keep "updateState", "uninstall" and "proposeState" event listeners on AppInstance. dApps will likely be most interested in events for ALL app instances, and only in specific cases be interested in events relating to specific app instances.
2) dApps don't need to know when an installation is proposed. Install proposals go through the Playground (later the Wallet). dApps only need to know whether an app instance was succesfully installed, or rejected. 
+ some renames

[CFjs] Update spec: move events to Provider, remove proposeInstall event

---

packages/cf.js/API_REFERENCE.md

- Add Node Protocol heading with methods and events
- Split AppDefinition into appId (on-chain address) and encodings
- Move install() to Provider
- Refer to Node Protocol methods and events for CFjs instance methods and events
- Leave anything with app manifest or proposing states TODO

[CFjs + Node] Rewrite/extend the CFjs.2 spec with Node Protocol

---

packages/cf.js/src/legacy/index.ts

these exported values in the namespace `cf.legacy` are not unused. deleting will prevent accidental uses of them from being added.

delete unused exports in cf.legacy

---

packages/playground/src/components/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/apps-list-item/apps-list-item.tsx
packages/playground/src/components/apps-list/apps-list.tsx

Components inserted via #277 were being instantiated directly on `<app-root />`, and I didn't notice that during the review. This PR moves the usage of `<apps-list />` to the `render()` function of  `<app-home />` and adds some initialization values for properties.

[playground] Moves usage of apps-list to app-home route

---

packages/playground/package.json
packages/playground/src/components/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/apps-list-item/apps-list-item.tsx
packages/playground/src/components/apps-list/apps-list.tsx
packages/playground/src/components/dapp-container/dapp-container.tsx
packages/playground/src/types.ts
packages/playground/src/utils/app-list.ts

This PR expands on previous work done in #277 and #278. A dApp icon is now clickable, transitioning to a route `/dapp/<app-slug>`, where the `<dapp-container />` component is instantiated, opening the dApp's URL.

[playground] Added support for opening a dApp

---

packages/playground/src/components/app-connection/app-connection.e2e.ts
packages/playground/src/components/app-connection/app-connection.scss
packages/playground/src/components/app-connection/app-connection.tsx

Adds a simple `connected` boolean, currently purely for UI purposes:

add connected state

---

packages/playground/src/assets/icon/menu-btn.svg
packages/playground/src/components/app-connection/app-connection.scss
packages/playground/src/components/app-drawer/app-drawer.e2e.ts
packages/playground/src/components/app-drawer/app-drawer.scss
packages/playground/src/components/app-drawer/app-drawer.spec.ts
packages/playground/src/components/app-drawer/app-drawer.tsx
packages/playground/src/components/app-header/app-header.scss
packages/playground/src/components/app-header/app-header.tsx
packages/playground/src/components/app-logo/app-logo.e2e.ts
packages/playground/src/components/app-logo/app-logo.scss
packages/playground/src/components/app-logo/app-logo.spec.ts
packages/playground/src/components/app-logo/app-logo.tsx
packages/playground/src/components/app-root/app-root.tsx

On mobile, the topbar is now nested away in a drawer (the closing animation looks smoother in person):
On pc, it continues to look like:

add menu drawer for mobile

---

package.json
yarn.lock

CircleCI has upgraded the version of yarn they run from `1.10.1` to `1.12.3` (ref: https://github.com/nodejs/docker-node/pull/944), causing builds to fail. 
However, netlify still uses `1.10`.
This PR updates the pinned yarn version to `^1.10` in order to cover both versions.

[monorepo] update yarn

---

build.sh
package.json

According to findings on #312, while we work on IIFE mode, we need to use symlinks to connect the dependencies. To keep `lerna` from breaking the build, we now use a bash script to arbitrarily build the packages in the order we need them to.
:warning: This should be reverted as soon as we fix Rollup.

[monorepo] Adds arbitrary order build script

---

packages/playground/package.json

Serializes stencil tests to prevent OOM errors.
The stencil documentation does not show any options to serialize directly through CLI, hence the separate commands.

Serialize stencil tests

---

packages/playground/src/components/layout/app-header/app-logo/app-logo.tsx

This PR fixes the event handler for the logo click to use the Stencil router instead of a regular link. This prevents a hard-refresh of the page.

[playground] Implements stencil-route-link for app-logo

---

packages/playground/src/components/layout/layout-header/header-account/header-account.spec.ts
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/components/layout/layout-header/header-content/header-content.tsx

To facilitate mocking interactions while we get ready to have real connections in the Playground, this PR adds a `fakeConnect` property to the account component, which will change the state of the header app to `{ authenticated: true }`.

[playground] Implements fakeConnect for <header-account>

---

packages/contracts/test/integration/countingGame.spec.ts
packages/contracts/test/integration/ticTacToe.spec.ts
packages/contracts/test/unit/appInstance.spec.ts

use `buildArtifacts` instead of `AbstractContract.fromArtifactName` where possible

[contracts] use buildArtifacts

---

package.json
tslint.json
yarn.lock

Since `tslint-microsoft-config` has finally left beta status for the v6.x branch, we can now use it to remove linting issues related to function names for iterators (i.e. `[Symbol.asyncIterator()]`).
:warning: In order to apply this change, it's possible that you need to reboot Visual Studio Code.
You can verify the linting rule works by putting an iterator function somewhere and running `yarn run tslint --project .` to confirm, in case Visual Studio Code gives false positives.
The maintainers at `tslint-config-airbnb` haven't released a new version with this library yet, hence the need for a local resolution.
This PR resolves #91.

[monorepo] Use tslint-microsoft-contrib@^6.0.0

---

packages/cf.js/rollup.config.js
packages/cf.js/src/legacy/app-instance.ts
packages/cf.js/src/legacy/app/index.ts
packages/cf.js/src/legacy/eth-balance-refund-app.ts
packages/cf.js/src/legacy/node/index.ts
packages/cf.js/src/legacy/types.ts
packages/cf.js/src/legacy/utils/free-balance.ts
packages/cf.js/src/legacy/utils/peer-balance.ts
packages/cf.js/src/legacy/utils/serializer.ts
packages/cf.js/src/utils/abi.ts
packages/cf.js/src/utils/signature.ts
packages/cf.js/test/app-factory.spec.ts
packages/cf.js/test/utils/signature.spec.ts
packages/contracts/test/app-registry.spec.ts
packages/node/src/channels.ts
packages/node/src/models.ts
packages/node/src/node.ts
packages/node/src/utils.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/node-communication.spec.ts
packages/node/test/integration/node-store.spec.ts
packages/node/test/integration/utils.ts

Replace ethers usage to always import from module

---

packages/contracts/contracts/StateChannelTransaction.sol
packages/machine/test/unit/ethereum/install.spec.ts
packages/machine/test/unit/ethereum/setup.spec.ts

For clarity, this PR renames `appCfAddress` to `appInstanceId` in the `executeAppConditionalTransaction` method of the `StateChannelTransaction` contract:
https://github.com/counterfactual/monorepo/blob/4234063325dabe8738bd7db1e2860fdf502d8e8c/packages/contracts/contracts/StateChannelTransaction.sol#L24-L30

Rename appCfAddress to appInstanceId

---

packages/dapp-high-roller/tsconfig.json
packages/playground/tsconfig.json

~Removes `dom` from the `lib` key on the `tsconfig.json` inside `dapp-high-roller` because it is already declared in the root level `tsconfig.json`:~
Removes some duplicated fields from the root `tsconfig.json`

[dapp-high-roller] Clean up tsconfig.json

---

packages/machine/scripts/test.sh
packages/machine/src/ethereum/install-commitment.ts
packages/machine/test/integration/bignumber-jest-matcher.ts
packages/machine/test/integration/connect-ganache.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/integration/random-signing-keys.ts
packages/machine/test/integration/setup-then-set-state.spec.ts

Unfortunately it breaks parallelism so I had to add `--runInBand` back. I tried listening to events to uniquely identify transactions being submitted to ensure the callback in the integration tests runs for the correct multisig, but it seems like not all events are returned from `ethers.Contract.prototype.on`'s event emitter.
Also this PR includes two fixes that needed to be there:
- https://github.com/counterfactual/monorepo/pull/381
- https://github.com/counterfactual/monorepo/pull/382

[machine] Add an integration test for InstallCommitment

---

packages/contracts/contracts/libs/LibStateChannelApp.sol

Found this ambiguous reference to "app" while editing specs.

[contracts] [docs] clarify reference to App

---

packages/apps/tsconfig.json
packages/node-provider/rollup.config.js
packages/node-provider/test/unit/node-provider.spec.ts
packages/node-provider/test/utils/message-api-mocks.ts
packages/node-provider/tsconfig.json
yarn.lock

Adds the rule `"noImplicitAny": true` to `tsconfig.json` files for packages whose source code already has no implicit `any`s.

Add noImplicitAny to tsconfigs that already comply

---

packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/web3-connector/web3-connector.tsx
packages/playground/src/components/widgets/widget-connection/widget-connection.tsx
packages/playground/src/data/account.tsx
packages/playground/src/data/network.tsx
packages/playground/src/index.html
yarn.lock

This PR will expose the following functionality to the Playground:

[playground] Integrates Metamask account

---

packages/node/src/methods/app-instance-operations.ts
packages/node/src/methods/install-operations.ts
packages/node/src/methods/multisig-operations.ts
packages/node/src/methods/request-handler.ts
packages/node/src/node.ts

Adds an instance of an `InstructionExecutor` to the `Node` and threads it through into all `methods` by adding an `InstructionExecutor` as the 3rd param in all `RequestHandler`-compliant methods.

[node] Add InstructionExecutor to requests to methods

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a checkbox at the end of the PR template to provide a reminder to check for a  functional deploy preview.

Add reminder to check deploy preview

---

packages/machine/src/instruction-executor.ts
packages/machine/src/middleware.ts
packages/machine/src/opcodes.ts
packages/machine/src/types.ts
packages/machine/test/unit/instruction-executor.spec.ts

- `Middleware` -> `MiddlewareContainer`
- `InstructionMiddlewareCallback` -> `Middleware`
- all other types deleted / inlined
- scope is now stored only in key
- delete `STATE_TRANSITION_PROPOSE` opcode

[machine] Opcode, middleware cleanup

---

README.md

Yarn version was stated as v1.10.1. However, now that is the minimum version.

[monorepo] Update README regarding Yarn Install

---

packages/dapp-high-roller/src/components/app-game-coin/app-game-coin.scss

Halves the coin size on mobile.

adjust coin size on mobile

---

packages/contracts/scripts/test.sh
packages/machine/scripts/test.sh

Previously, if an existing ganache instance is running, `test.sh`'s invocation of ganache-cli would fail silently and the `kill` call would fail.
Why an existing instance might be running: user ran it in another tab, or (in my case) `ganache-cli` gets reparented to PID 1 for some reason.

[contracts] kill ganache before starting tests

---

packages/contracts/contracts/ETHVirtualAppAgreement.sol
packages/contracts/contracts/StateChannelTransaction.sol
packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinCancelChallenge.sol
packages/contracts/contracts/mixins/MixinSetResolution.sol
packages/contracts/contracts/mixins/MixinSetState.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/test/app-registry-new.spec.ts
packages/contracts/test/app-registry.spec.ts
packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/contracts/test/utils/index.ts
packages/machine/src/ethereum/install-commitment.ts
packages/machine/src/ethereum/setup-commitment.ts
packages/machine/src/models/app-instance.ts
packages/machine/src/models/state-channel.ts
packages/machine/src/protocol-types-tbd.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/integration/setup-then-set-state.spec.ts
packages/machine/test/unit/ethereum/install-commitment.spec.ts
packages/machine/test/unit/ethereum/setup-commitment.spec.ts
packages/machine/test/unit/ethereum/uninstall-commitment.spec.ts
packages/machine/test/unit/models/state-channel/install.spec.ts
packages/machine/test/unit/models/state-channel/set-state.spec.ts
packages/machine/test/unit/models/state-channel/uninstall-app.spec.ts
packages/node/src/models.ts

Due to historical reasons, the word `AppInstanceId` in the monorepo refers to two separate things:
- something generated by cf.js via a call to `uuid.v4()` which looks like `9956b015-46b2-4e05-8528-54071bbcfa38`
- the `keccak256` hash of an `AppIdentity` struct, which looks like `c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`
(notice that they do not even encode the same number of bits)
This PR changes  occurrences of `AppInstanceId` referring to the latter to `AppIdentityHash`

[monorepo] Rename AppInstanceId to AppInstanceIdentityHash

---

packages/machine/src/instruction-executor.ts
packages/machine/src/protocol-types-tbd.ts
packages/machine/src/protocol/update.ts

This change was reverted in #425 due to it being a dependency of #417

[machine] rename UpdateData -> UpdateParams

---

packages/cf.js/src/utils/signature.ts
packages/cf.js/test/utils/signature.spec.ts
packages/machine/src/ethereum/multisend-commitment.ts
packages/machine/src/ethereum/multisig-commitment.ts
packages/machine/src/ethereum/set-state-commitment.ts
packages/machine/src/ethereum/setup-commitment.ts
packages/machine/src/ethereum/utils/signature.ts
packages/machine/src/instruction-executor.ts
packages/machine/src/opcodes.ts
packages/machine/src/protocol-types-tbd.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/setup.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/src/types.ts
packages/machine/test/mocks.ts
packages/machine/test/unit/ethereum/set-state-commitment.spec.ts
packages/machine/test/unit/ethereum/setup-commitment.spec.ts
packages/machine/test/unit/ethereum/uninstall-commitment.spec.ts
packages/machine/test/unit/instruction-executor.spec.ts
packages/node/test/integration/utils.ts

These are mostly pulled out from #419.
- rename `signaturesToSortedBytes` to `signaturesToBytesSortedBySignerAddress`
- rename `MultisigTransactionCommitment` to `MultisigCommitment`
- rename `Context::operation` to `Context::commitment`
- mark `STATE_TRANSITION_COMMIT` and `OP_SIGN_VALIDATE` as unused/deprecated via comments
- specify that `OP_SIGN` should not be doing any decision-making
- delete `MockResponseSink` (unused)
- abstract out the random-address `NetworkContext`s
- enforce type of `EMPTY_NETWORK`

[monorepo] miscellaneous cleanup

---

packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinSetResolution.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/contracts/test/utils/index.ts
packages/dapp-high-roller/src/data/types.ts
packages/machine/src/ethereum/utils/encodings.ts
packages/machine/src/ethereum/utils/free-balance.ts
packages/machine/src/models/app-instance.ts
packages/machine/test/unit/ethereum/install-commitment.spec.ts
packages/machine/test/unit/ethereum/set-state-commitment.spec.ts
packages/machine/test/unit/ethereum/uninstall-commitment.spec.ts
packages/types/src/app-instance.ts
yarn.lock

Since #477 we no longer need this value to be a part of the `AppIdentity` object. Instead, we only need the `address`.

[contracts, machine] Remove appInterfaceHash from AppIdentity

---

packages/cf.js/README.md
packages/contracts/README.md
packages/dapp-high-roller/README.md
packages/machine/README.md
packages/playground-server/README.md
packages/playground/README.md
packages/typescript-typings/README.md

I updated the wording for **Make sure you have Yarn v1.10.1 installed or higher** a few days ago but didn't update it for all of the README.md files, this completes that.
Also I noticed that Header links for each README was pointing to an incorrect URL that was returning a 404. Fixed that as well.
There is still an issue with images in the top right of each README. I am not sure what image is supposed to be there. The src points to https://static1.squarespace.com/static/59ee6243268b96cc1fb2b14a/t/5af73bca1ae6cf80fc1cc250/1529369816810/?format=1500w
However this returns a `Website Expired` page when visited.

[Documentation] Fix README files regarding yarn version and package links

---

packages/playground/src/components/dapp-container/dapp-container.tsx

DappContainer was echoing messages instead of actually feeding messages to the Node back and forth.

[playground] Fixes Node/dApp communication

---

packages/node/src/node.ts

Requirement in order to use `this.signer` for registering a middleware on `OP_SIGN`

Make instructionExecutor member of Node

---

packages/node-provider/src/node-provider.ts

This PR adds support for debugging the `node-provider` package.
- If an environment variable `CF_NODE_PROVIDER_DEBUG` is detected, a log handler suited for shell-based consoles will take care of printing messages.
- If a key in `window.localStorage` called `cf:node-provider:debug` is set to `true` in the **dApp's** context, a formatted/coloured log handler will print messages in the browser's console.

[node-provider] Adds debug mode and log messages

---

packages/playground-server/src/api.ts
packages/playground-server/src/middleware/error.ts

API 4xx errors were being obscured by a CORS middleware misconfiguration. This PR fixes it.

[playground-server] Fixes error control affected by CORS middleware

---

packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground/src/components/dapp-container/dapp-container.tsx

dApps no longer depend on `/api/matchmake`'s `user` part of the response, because now they can request data to the Playground via `postMessage`.
**How does this work?**
1) dApp emits a request:
```js
window.parent.postMessage("playground:request:user");
```
2) Playground receives the message and posts back:
```js
frameWindow.postMessage(["playground:response:user", JSON.stringify(user)].join("|"));
```
3) dApp receives the response while listening to the `message` event:
```js
if (message.startsWith("playground:response:user") {
// Extract the data and store it in the dApp's local state
}
```

[playground] [dapp-high-roller] [dapp-tic-tac-toe] Implements user data sharing across postMessage for dApps

---

packages/playground-server/src/controllers/create-account.ts
packages/playground-server/src/types.ts
packages/playground-server/test/api.spec.ts
packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/data/playground-api-client.ts

This PR implements the creation and local storage of a token upon account registration. The `/api/create-account` endpoint now includes a `token` property in its response.
On the client-side, the AccountRegister component picks up the property and pushes it to `localStorage`, under the key `playground:user:token`.

[playground-server] [playground] Creates and sends a token upon account registration

---

packages/node/src/events/install/controller.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/request-handler.ts

This drops `self` in referring to a Node's address to eliminate redundancy.

[node] Update term referring to Node's own address

---

packages/cf.js/API_REFERENCE.md
packages/cf.js/src/app-factory.ts
packages/cf.js/test/app-factory.spec.ts
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/src/data/types.ts
packages/node/src/events/install/controller.ts
packages/node/src/events/install/operation.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/services.ts
packages/node/src/utils.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/get-state.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/services/mock-messaging-service.ts
packages/playground/src/data/counterfactual.ts
packages/playground/src/data/firebase.ts
packages/types/src/node-protocol.ts
packages/types/src/node.ts

To be consistent, this replaces the term `peerAddress` with `respondingAddress` to align with and reflect the recent term that was updated in the machine.

[monorepo] Replace peerAddress with respondingAddress

---

packages/contracts/contracts/state-deposit-holders/MinimumViableMultisig.sol

Adds the notice: "Note that two transactions with identical values of (to, value, data, op) are not distinguished". Also deletes some param annotations that are passed from elsewhere.

[contracts] add disclaimer to MinimumViableMultisig::getTransactionHash

---

packages/node-provider/rollup.config.js
packages/node/rollup.config.js

These aren't recognized by rollup

[monorepo] Remove unknown rollup options

---

packages/machine/src/protocol/setup.ts
packages/node/src/events/protocol-message/controller.ts
packages/node/src/node.ts

This implements `IO_SEND` and adds some supporting mocks to ensure
it actually works.
So what is going on here is that real messages are being sent _from_ nodes however when they are expecting to receive the message, they aren't actually listening yet (that is a forthcoming PR or commit for `IO_WAIT`). Instead, that behaviour is mocked out.

[node] Initial implementation of IO_SEND

---

packages/node/src/api-router.ts
packages/node/src/events/index.ts
packages/node/src/events/reject-install/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/index.ts
packages/node/src/store.ts
packages/node/src/types.ts
packages/node/test/integration/reject-install.spec.ts
packages/node/test/integration/utils.ts

This implements the [`rejectInstall`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-rejectInstall) public API method.
Note this is only for non-virtual AppInstances. Implementation for rejecting a Virtual AppInstance will follow this.

[node] Implements rejectInstall

---

packages/dapp-high-roller/src/components/app-game/app-game.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/src/components/app-waiting/app-waiting.tsx
packages/dapp-high-roller/src/data/mock-node-provider.ts

Add opponent name to waiting screen
In addition this fixes some issues and errors that were being thrown when running in standalone.
Another issue is that the API for getting a user was updated, but the usage of that user, (renamed to account) wasn't updated.

[dapp-high-roller] Add opponent name to waiting screen

---

packages/node/package.json
yarn.lock

PR #553 updated `firebase` in the `node` package, which silently broke the build process for the Playground, due to (apparently) how it injects CommonJS-style polyfills.
The [`master` deploy for this PR](https://app.netlify.com/sites/playground-staging/deploys/5c41faee6424350008049009) was never successful due to a timeout, so there are no logs there, but the [_preview_ deploy](https://app.netlify.com/sites/playground-staging/deploys/5c41f95af2f37200087f92a7) shows the following error:
```
1:09:58 PM: [09:58.0]  Please wait while required dependencies are updated. This may
1:09:58 PM:            take a few moments and will only be required for the initial
1:09:58 PM:            run.
1:09:58 PM: [09:58.0]  installing dependency: workbox-build ...
1:10:02 PM: npm
1:10:02 PM:  notice created …
```

[node] Reverts firebase@5.8.0 to firebase@5.7.1

---

packages/node/src/api-router.ts
packages/node/src/events/index.ts
packages/node/src/events/reject-install-virtual/controller.ts
packages/node/src/methods/app-instance/reject-install-virtual/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/index.ts
packages/node/src/types.ts
packages/node/test/integration/reject-install-virtual.spec.ts
packages/node/test/integration/reject-install.spec.ts

This is the follow up to https://github.com/counterfactual/monorepo/pull/558. It implements support for making the [`rejectInstall`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-rejectInstall) call on proposed Virtual AppInstances.

[node] Implements rejectInstall for Virtual AppInstance

---

packages/node-provider/package.json
packages/node/package.json

When `0.0.2` of `@counterfactual/cf.js` was published, we left both the `Node` and `NodeProvider` packages pointing to the old version, making the monorepo to use an incorrect version.

[node] [node-provider] Fixes CF.js version

---

packages/dapp-tic-tac-toe/public/index.html

Since #564 got merged, TTT must inject a different dependency for a browser version of `uuid`.

[dapp-tic-tac-toe] Replaces cuid with uuid

---

packages/cf.js/package.json
packages/cf.js/rollup.config.js
yarn.lock

This bundles some of the dependencies for the @countrefactual/cf.js package in its dist, but notably leaves out:
- `ethers`
- `eventemitter3`
- `uuid`
These can reliably be fetched from CDNs.

[cf.js] Bundle dependencies for distribution

---

packages/node/src/events/multisig-created/controller.ts
packages/node/test/unit/install.spec.ts

since `setupChannel` already populates an empty ETH free balance, these calls are unnecessary

[monorepo] remove some uses of setFreeBalanceFor

---

packages/apps/contracts/HighRollerApp.sol

Ternary expression in getTurnTaker of HighRollerApp contract was flipped in a recent PR. This reverts that
Caused by: #584

[dapp-high-roller] Revert back original order in getTurnTaker ternary

---

packages/dapp-tic-tac-toe/src/App.js

Fix calling connect function with a redundant param. 
The `connect` function expects 0 arguments and it is called with `nodeProvider` redundantly.

[dapp-tic-tac-toe] Fix calling connect function with a redundant param

---

packages/apps/contracts/HighRollerApp.sol

In the High Roller Contract we calculate the `randomSalt` to be used as a random bytes32 seed for generating 4 dice rolls.
This salt is created by doing: `keccak256(abi.encodePacked(num1 * num2));`
If one of the numbers is 0, the output is always the same no matter what the other player chooses.
This adds an assertion that neither of the player numbers is 0.

[dapp-high-roller] Assert that numbers passed in by players in HighRoller are not 0

---

packages/apps/contracts/CountingApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/TicTacToeApp.sol

In a recent PR #584 we added `encodedState` and `encodedAction` to our dapp contract code. This is because they should be an instance of CounterfactualApp contract.
This adds a few contracts that were missed.
One contract that I ran into issues with is `PaymentApp`. Adding the `is CounterfactualApp` caused tests for the contract to fail. @snario Could you help me look into this?
Related: #584

[apps] Make apps instance of CounterfactualApp

---

packages/playground/src/components/widgets/widget-screen/widget-screen.scss

[playground] Fixes misalignment for logo in widget-screen

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground-server/src/controllers/matchmaking.ts
packages/playground-server/src/db.ts
packages/playground-server/src/types.ts
packages/playground/src/components/dapp-container/dapp-container.tsx

This PR introduces a new flag called `playground:matchmakeWith`, useful for dev/testing purposes.
In order to be used, this flag must be set in the Playground's `localStorage`, like this:
This flag will be passed to the dApp as part of the `playground:request:user` message response. If the flag is set, it'll be then passed as part of the request to the Matchmaking API:
```json
{ "data": { "attributes": { "matchmakeWith": "c" } } }
```
When the Playground Server parses this request, it'll return the specified user's data, instead of running the matchmaking algorithm.
if the flag is not set, matchmaking will work as usual.

[playground] [playground-server] [dapp-high-roller] [dapp-tic-tac-toe] Adds support for "playground:matchmakeWith" flag

---

packages/contracts/networks/3.json

This adds the addresses the contracts have been deployed to on Ropsten.

[contracts] Add migrations for Ropsten

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/layout/layout-header/header-account-info/header-account-info.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/components/web3-connector/web3-connector.tsx
packages/playground/src/components/widgets/widget-spinner/widget-spinner.scss
packages/playground/src/components/widgets/widget-spinner/widget-spinner.tsx
packages/playground/src/data/account.tsx
packages/typescript-typings/types/ethers/index.d.ts

This PR refactors the way deposits are made and account balances are read, introducing the concept of _unconfirmed balances_. 
Since a transaction takes time to be confirmed by the blockchain, the account state stores an _unconfirmed balance_ which is the amount the user has deposited upon registration. While the value of `unconfirmedBalance` exists, a spinner will show next to the account balance on the UI. 
The provider listens to an address-type event to get the updated balance. When the listener is triggered, it removes the `unconfirmedBalance` value and sets the true balance, hiding the spinner.
**Preview:**

[playground] Implements event-driven balance updates + unconfirmed balance UI

---

packages/playground/src/data/playground-api-client.ts

This PR adds a `timeout()` function to the API client, wrapping the `window.fetch()` calls for HTTP GET and POST operations. This ensures that if a request hangs up on a pending state, it'll be cancelled.

[playground] Adds timeout to API requests from the client

---

packages/machine/src/instruction-executor.ts
packages/node/src/events/install/controller.ts
packages/node/src/events/protocol-message/controller.ts

The previous name `dispatchReceivedMessage` is potentially ambiguous

rename dispatchReceivedMessage to runProtocolWithMessage

---

packages/dapp-high-roller/src/components/app-game-coins/app-game-coins.tsx
packages/dapp-high-roller/src/components/app-game-die/app-game-die.scss
packages/dapp-high-roller/src/components/app-game-status/app-game-status.tsx
packages/dapp-high-roller/src/components/app-game/app-game.tsx
packages/dapp-high-roller/src/components/app-logo/app-logo.tsx
packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-waiting/app-waiting.tsx
packages/dapp-high-roller/src/utils/utils.ts
packages/playground-server/registry.json
packages/playground-server/registry.local.json
packages/typescript-typings/types/ethers/index.d.ts

This PR features:
- Winning detection logic with the REVEAL stage
- Better animation UI triggers to reflect what's actually happening in the game state
- Opponent data for the waiting room on the counterparty's side
**Preview**
A tie:
A win/lose:

[dapp-high-roller] Implements REVEAL stage, improves die animation triggers

---

build.sh

This PR makes the build process exit-code aware, so if any package's `build` task fails, it'll stop the build pipeline.

[monorepo] Returns non-zero exit code for yarn build

---

packages/contracts/scripts/test.sh
packages/machine/scripts/test.sh

unfortunately `lsof` is sometimes not present on the CI machines. even more unfortunately there doesn't seem to be a POSIX utility that has the same functionality we need

[monorepo] do not use lsof if not present

---

packages/machine/test/integration/virtual-app-set-state-commitment.spec.ts
patches/scrypt+6.0.3.patch

```sh
$ yarn test virtual-app-set
yarn run v1.10.1
$ ./scripts/test.sh virtual-app-set
📧 Reading environment values from .env, defaulting to values in test.sh
⛓ Starting ganache-cli at http://127.0.0.1:8546 (network_id: 8888888)
⚙️ Running migrations with build artifacts from @counterfactual/contracts
🧪 Starting jest test suites
PASS  test/integration/virtual-app-set-state-commitment.spec.ts (5.023s)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        5.833s
Ran all test suites matching /virtual-app-set/i.
✨  Done in 15.45s.
```

Fix problems in ldct/virtual-app-set-state-test

---

packages/playground/src/index.html

This fixes the following error:
```
Uncaught ReferenceError: hdnode is not defined
at node.js:2525
```

[playground] Exposes hdnode as required by the Node IIFE

---

packages/playground/src/data/playground-api-client.ts

Since #559 was merged, the Playground must call `/api/users/me` to get the user data from a token. 
This PR fixes a wrongful call to `/api/users`.

[playground] Fixes API call for current user

---

packages/playground-server/registry.local.json
packages/playground-server/src/resources/app/processor.ts

The `registry.local.json` file was using a non-JSONAPI-compliant data structure, making the App Registry endpoint fail when pointed to it. 
This PR fixes it.

[playground-server] Fixes data payload for registry.local

---

packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/data/counterfactual.ts

This PR updates account creation to use `publicIdentifier` instead of `address`.
:warning: **Important notice:** After this PR gets merged and deployed, currently-registered Playground accounts will no longer be valid. Any local/staging accounts must be wiped and re-created.

[playground] Uses Node.publicIdentifier instead of address

---

packages/dapp-high-roller/netlify.sh
packages/dapp-tic-tac-toe/netlify.sh

The `yarn netlify` commands for both dApps broke because of a change in the dependency order since #620. This PR fixes that.

[dapp-high-roller] [dapp-tic-tac-toe] Fixes build processes

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground-server/src/api.ts
packages/playground-server/src/middlewares/validate-signature.ts
packages/playground-server/src/resources/app/processor.ts
packages/playground-server/src/resources/matchmaking-request/processor.ts
packages/playground-server/src/resources/session-request/processor.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground/src/data/playground-api-client.ts
packages/playground/src/types.ts

This PR implements the following changes:
**`validateSignature()` is now called by passing it to `jsonApiKoa`**
`jsonapi-ts` includes `koa-bodyparser`, and in order to validate the signature we also need to inspect the request body. Reading the body a second time resulted in no request body available, therefore the processors couldn't be executed. `jsonapi-ts` now features a `middlewares` argument that injects those functions _after_ `koa-body` but _before_ the JSON API handler itself. This allowed account registration and login to work again.
**Matchmaking is now calling the correct API, and dApps are using the new response format**
Since `jsonapi-ts` support for `includes` is still WIP, we changed how the API responds to a matchmaking request. Instead of using relationships and …

[playground-server] [playground] [dapp-high-roller] [dapp-tic-tac-toe] Fixes signature validation, account registration and matchmaking problems

---

packages/playground/src/components/dapp-container/dapp-container.tsx

Fix spelling mistake `attachs` -> `attaches`

[playground] Fix spelling mistake `attachs` -> `attaches`

---

packages/playground-server/src/resources/matchmaking-request/processor.ts
packages/playground-server/test/api.spec.ts
packages/playground/src/data/playground-api-client.ts
packages/playground/src/types.ts

The Matchmaking API was trying to force-matchmake all requests due to bad checking of the flag's existence. This PR fixes the API to work as expected and adds an extra test case for the flag.

[playground] [playground-server] Fixes matchmaking bug when not using `matchmakeWith` flag

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/src/data/types.ts
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground/src/components/node-listener/dialogs/propose-install/dialog-propose-install.tsx

PR #719 renamed the following parameters in the API call for `proposeInstallVirtual`:
- initiatingAddress => proposedByIdentifier
- respondingAddress => proposedToIdentifier
These changes weren't applied to the Playground and the dApps, hence no install proposals could be executed.
This PR applies the new names where necessary.

[playground] [dapp-high-roller] [dapp-tic-tac-toe] Fixes proposeInstallVirtual call to use proposedByIdentifier & proposedToIdentifier

---

packages/playground/src/components/layout/layout-header/header-account/header-account.tsx

If there's an invalid token stored in `playground:user:token` and the API returns `HTTP 404`, this PR will make the Playground remove that invalid token.

[playground] Removes token if login from token fails

---

packages/playground-server/src/index.ts

Due to the API responding from time to time with an `HTTP 504` error code, we've increased the timeout up to 5 minutes.
This will be a temporary measure as we develop a fully asynchronous version of the registration flow.
:information_source: This PR requires immediate deployment to the server VPS.

[playground-server] Increases Node.js HTTP timeout to 5 minutes

---

packages/playground/src/components/widgets/widget-connection/widget-connection.tsx

This PR removes the "Mainnet" / "Testnet" labels next to the network name in the connection status component.
**Before**
**After**

[playground] Removes network type in <widget-connection>

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx

Fix estimating gas to be done with ethAddress not nodeAddress
This was causing an error to be thrown when proposeInstalling in High Roller

[dapp-high-roller] fix: Estimating gas to be done with ethAddress not nodeAddress

---

.circleci/config.yml

Reason is that I made changes to `yarn.lock` in #773 but the tests fail because it doesn't pick them up (I did _not_ change any `package.json` files)

[monorepo] Save dependencies cache w/ yarn.lock in key

---

packages/apps/package.json
packages/cf.js/package.json
packages/contracts/package.json
packages/machine/package.json
packages/node-provider/package.json
packages/node/package.json
packages/types/package.json
packages/typescript-typings/package.json

Previously we pegged it to the github repo because the `HDNode` code wasn't pushed yet.

[monorepo] Get ethers back on semver

---

packages/node/src/node.ts

Can potentially solve some issues with messages being received from the same counterparty that are mistakenly perceived as being intended for an `IO_SEND_AND_WAIT` hook that it is not meant for.

[node] Implement ioDeferral handling based on unique message, not just sender

---

packages/machine/truffle-config.js
yarn.lock

Should fix the issue of the machine tests failing after running `yarn` (since `yarn` will fix `truffle`'s dependency on `solc` to `0.5.0` which makes the tests fail).

[machine] Fixes solc to 0.5.3 in truffle config

---

.circleci/config.yml
packages/playground-server/package.json
yarn.lock

We no longer install `@ebryn/jsonapi-ts` as a git dependency. This will remove caching problems we've faced before with this consumption method, as well as enable us to stop installing TypeScript globally on CircleCI.

[playground-server] Consumes jsonapi-ts as an NPM package

---

packages/playground/src/components/node-listener/node-listener.tsx

The modal dialogs weren't opening because `this.networkState.web3Detected` was `undefined` and so `bindNodeEvents` was never running.

correctly observe web3dectect to ensure that node events are bound

---

packages/node-provider/src/node-provider.ts
packages/playground/src/components/app-home/app-home/app-home.scss
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx

This PR implements feature detection code for Local Storage. It also includes UA sniffing to attempt to guide the user in the correct way to disable whatever is blocking LS from being used. 
For the Node Provider, it enables a third debug-mode by scanning the URL for the hash `#cf:node-provider:debug`. 
:thought_balloon: _Fun fact:_ Stencil Router relies on Session Storage to work, so in order to show the error screen, it was necessary to bypass the router altogether and forcefully render the `app-home` component. Also, since everything is wrapped on the `node-listener` component, which also uses LS, if it's not enabled, the component isn't rendered.
**Example screen on Chrome:**

[playground] [node-provider] Shows error screen if LocalStorage is not available

---

packages/cf.js/API_REFERENCE.md
packages/node/src/methods/state-channel/create/controller.ts
packages/playground-server/src/db.ts
packages/playground-server/src/node.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground-server/test/api.spec.ts
packages/types/src/node-protocol.ts

The usage of `.once` was wrong. The playground server needs to listen to all `CREATE_CHANNEL` events and handle them accordingly to bind actual on-chain deployed addresses to `User` objects.
Included in this PR is a MVP of this functionality. Perhaps not the optimal design, but it works.

Move .once to a .on for CREATE_CHANNEL

---

package.json
packages/apps/package.json
packages/apps/tsconfig.json
packages/apps/waffle.json
packages/contracts/package.json
packages/contracts/tsconfig.json
packages/contracts/waffle.json
packages/dapp-high-roller/package.json
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/tsconfig.json
packages/dapp-tic-tac-toe/package.json
packages/node-provider/package.json
packages/playground-server/package.json
packages/playground-server/src/errors.ts
packages/playground-server/tsconfig.heroku.json
packages/playground-server/tsconfig.json
packages/playground/package.json
packages/types/tsconfig.json
packages/typescript-typings/package.json
patches/@resolver-engine+imports-fs+0.3.2.patch
tsconfig.json
yarn.lock

Did a refresh of my local repo while debugging something and I noticed that if you tried to run `yarn` without a `yarn.lock` some miscellaneous errors popped up. This fixes those.
1. `ethereum-waffle` has an issue with a dependency (https://github.com/EthWorks/Waffle/issues/85). Added a patch. 
2. `ethereum-waffle` specifies `solc@^0.5` which gets `0.5.4` which has a bug (https://github.com/ethereum/solidity/issues/5997). Fixed the version in `waffle.json`. Also added an issue 8 days ago https://github.com/EthWorks/Waffle/issues/78.
3. Upgraded some packages. FIxes #436 
4. Rollup does not support `module: "commonjs"` to changed to `esnext` where applicable.

Miscellaneous repo improvements to make dev env work with fresh yarn.lock

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/node-listener/node-listener.tsx
packages/playground/src/components/webthree-connector/webthree-connector.tsx
packages/playground/src/data/account.tsx
packages/playground/src/data/counterfactual.ts
packages/playground/src/data/wallet.tsx

Incremental PR. Makes sense for `provider` and `signer` to be properties of the wallet and not of the account (which represents your account with the `playground-server`)

[playground] Move provider and signer into WalletState

---

packages/machine/src/enums.ts
packages/machine/src/index.ts
packages/machine/src/middleware.ts
packages/machine/src/protocol/install-virtual-app.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/setup.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/src/protocol/withdraw-eth.ts
packages/machine/src/types.ts
packages/machine/test/unit/instruction-executor.spec.ts
packages/node/src/events/protocol-message/controller.ts
packages/node/src/node.ts

- rename `STATE_TRANSITION_COMMIT ` -> `WRITE_COMMITMENT`, since the state commitment change actually happens outside of any middlewares
- add `context.finalCommitment`, for `WRITE_COMMITMENT` to read
- use `context.finalCommitment` with withdraw and setup
- add actual signing to `instruction-executor.spec.ts` to avoid errors
- export more params via `machine` instead of `dist`

[machine,node] commitment store cleanup

---

packages/dapp-high-roller/src/components/app-root/app-root.scss
packages/dapp-high-roller/src/components/app-root/app-root.spec.ts
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/RouterListener.jsx
packages/playground/src/components/dapp-container/dapp-container.tsx

This PR implements resumability by sending the dApps' URL to the Playground so when the user refreshes, the dApp's iframe can be loaded with the last known URL. 
:construction: Pending to test if the game state resumes where it left (specially in High Roller). 
**Some notes:**
- `stencil-router` has no support for listening to route changes, so I'm forced to use `hash` routing on the High Roller dApp and listen to `popstate` events. Browser-mode routing isn't event-driven, and polling is not a preferred solution.
- The `app-root` component now delegates control to the Router after it's finished processing the user data sent via the `playground:response:user` postMessage() reply.

[playground] [dapp-high-roller] [dapp-tic-tac-toe] Implements dApp resumability

---

packages/playground/src/components/app-home/app-home/app-home.tsx

Earlier text was ambiguous between whether or not this was for real funds on main net or a demo on Ropsten. Changed to clarify.

clarified explanation text to say that this is a demo on Ropsten

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/Wager.jsx

This PR fixes the form validation for the bet amounts on both dApps' wager screens. 
Setting a `step` parameter on the input also limits the precision of the decimal number the user can enter into the numeric field. The solution was to add more decimal digits to the number.

[dapp-high-roller] [dapp-tic-tac-toe] Allows more precise decimals in the dApps' wager screens

---

packages/node/src/methods/controller.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/withdraw/controller.ts

Useful for situations when the method will throw but you could know that before its at-bat.
Example:
- Clicking Withdraw or Deposit while Withdraw or Deposit is pending

[node] Add beforeExecution and afterExecution to Node

---

packages/playground/src/components/layout/layout-header/header-content/header-content.tsx
packages/playground/src/components/widgets/widget-dev-flags/widget-dev-flags.scss
packages/playground/src/components/widgets/widget-dev-flags/widget-dev-flags.tsx
packages/playground/src/components/widgets/widget-dialog/widget-dialog.scss
packages/playground/src/components/widgets/widget-dialog/widget-dialog.tsx

This PR adds a `<widget-dev-flags />` component to monitor whatever `playground:*` flags we want to monitor in the Playground UI. It also provides a utility function to unset any of those flags.
**Currently monitored flags**
- `playground:matchmakeWith`
**Preview**

[playground] Adds widget-dev-flags component to monitor `playground:*` dev flags

---

packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/app-home/app-home/app-home.scss
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-home/apps-list-item/apps-list-item.tsx
packages/playground/src/components/app-home/apps-list/apps-list.scss
packages/playground/src/components/app-home/apps-list/apps-list.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/widgets/widget-spinner/widget-spinner.scss
packages/playground/src/components/widgets/widget-spinner/widget-spinner.tsx
packages/playground/src/data/app-registry.tsx
packages/playground/src/data/wallet.tsx

This PR introduces an UI blocker to prevent access to the dApps until the state channel is fully prepared.
It also unifies the currently two implemented spinners into a single widget. :) 
Balance check is done via polling, eventually it can be improved to a transaction array check-up.
**Preview**

[playground] Prevents the user from playing any dApps until the state channel has been collateralized

---

packages/playground/src/components/widgets/widget-spinner/widget-spinner.scss

This ensures the Etherscan link being mentioned in the UI is clickable.

[playground] Fix visibility of etherscan link

---

packages/playground/src/components/app-root/app-root.tsx

The Playground UI had a buggy implementation of a retry policy to fetch the multisig address, due to the use of `setTimeout` without properly wiring it to promises. This PR implements a `delay()` method as seen in 5132b7101bc860a68e601eb5854b2f606ae1274d.
**Preview**

[playground] Fixes multisig fetching async bug

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/Wager.jsx

Since the Playground now uses safe deposits through the Node, gas estimates are no longer necessary. This PR removes the validation checks for both dapps on their wager screens.

[dapp-high-roller] [dapp-tic-tac-toe] Removes gas check on wager deposits

---

packages/playground/src/components/dapp-container/dapp-container.tsx

This handles the previously uncaught error

[playground] Catch undefined multisig error

---

packages/dapp-high-roller/src/components/app-logo/app-logo.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/playground-server/.env-cmdrc
yarn.lock

Due to [this issue](https://github.com/ionic-team/stencil-router/issues/79), only `stencil-route` components get the router history injected into them. This means that other components (such as the `app-provider`) do not have access to `this,history`, which in turn is preventing the redirect from working.
To get around this issue, I pass the router history from a route element up to the `app-root` and then back down to the `app-provider`. Once the StencilRouter issue is fixed, we'll be able to simply use `injectHistory` within the `app-provider`.

[dapp-high-roller] fix routing bug

---

packages/cf.js/src/provider.ts

Because the forthcoming #927 PR adds a bunch of `eth_call`s inside the protocols, the API requests can take a while. Uninstall virtual app for example takes like 8 seconds locally. We can improve this in the future by using an local JS based EVM interpreter. `runCode` from here: https://github.com/ethereumjs/ethereumjs-vm works

Increase node provider api timeout

---

packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/request-handler.ts

Locally when testing it needs to be `1` because `ganache-cli` does not progress blocks unless you tell it to. However on staging and other normal environments we want some reasonable number for the testnet. When I have been testing, 3 seems to work.

[node] Add a block num confirmation property on request handler

---

packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/Game.jsx
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/dapp-tic-tac-toe/src/components/Board.jsx
packages/dapp-tic-tac-toe/src/index.css

1. The framework requires you use the 0th child keys for payout addresses atm
2. Added disable UI when waiting for the API to return so you can't double click and get in a weird state

[ttt] Update TTT dapp

---

packages/dapp-tic-tac-toe/package.json

Removes the publish config info so the package can be deployed.
https://circleci.com/gh/counterfactual/monorepo/22906?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

[dapp-tic-tac-toe] Remove publish config from TTT dapp

---

packages/playground-server/src/resources/user/processor.ts

When a new user tries to register, if the multisig deployment fails server side, then the registration will not be considered successful.
If the user tries to register again, they can't because they'll receive the error "User already registered."
This ensures that the user is saved if and only if the multisig deployment transaction is successfully sent to the network. If it is not, the user is not saved and hence the user can try to register again.

[playground-server] Create user iff multisig deployment tx is successfully sent to network

---

packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx

* validate that deposit is not larger than eth account balance
* force ttt players to bet .1 eth
* add button beneath deposit forms that links to ropsten faucet

[playground][dapp-tic-tac-toe] balance safe guards and test faucet link

---

packages/machine/package.json
packages/machine/src/protocol/utils/get-resolution-increments.ts
packages/node/package.json
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/request-handler.ts
packages/playground-server/package.json
packages/playground-server/src/node.ts
packages/playground/package.json
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/src/index.ts

- Added retry logic of 15 attempts, waits 1 second * numAttempts per attempt
- Uses Infura ONLY as the backend versus Infura OR Etherscan
- Confirmations needed is now 1 block not 4 (since we were using confirmations as a proxy of waiting time anyway)

[machine] Add retry logic for fetching blockchain state on resolve

---

packages/dapp-tic-tac-toe/src/Game.jsx

Currently, there's a delay after the user selects a square on the ttt board while we wait for the action protocol to complete. This pr causes the board to update immediately.

[dapp-tic-tac-toe] instantly update board after click

---

packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
yarn.lock

The deposit form has a link to the test network faucet. This changes the link from ropsten to kovan.

[playground] link to kovan faucet

---

packages/playground-server/src/api.ts
packages/playground-server/src/db.ts
packages/playground-server/src/node.ts
packages/playground-server/src/resources/multisig-deploy/processor.ts
packages/playground-server/src/resources/multisig-deploy/resource.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/components/app-home/apps-list/apps-list.tsx
packages/playground/src/components/app-root/app-root.spec.ts
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/data/playground-api-client.ts
packages/playground/src/types.ts

This PR refactors the way account creation + multisig deployment work in order to get rid of most of the bugs affecting async registration, collateralization UI blocking and such.
Most of the work takes place in the `/register` route, where the `account-register` component now is fully aware of the three stages of account creation:
1. Metamask signature
2. Database record insertion
3. Multisig deployment
Once all three steps are completed, the user is redirected to the `/deposit` route, where it'll make its first deposit. 
Once the balance changes as much as the deposit, we consider collateralization completed, and allow access to the dApps.

[playground-server] [playgruound] Refactors account creation and deposits to avoid invalid UI blockage

---

packages/dapp-high-roller/src/components/app-root/app-root.tsx

Fixes randomness logic in high roller for contract.
Logic for determining randomness in the Solidity contract was this:
`randomness = keccak256(abi.encodePacked(num1 * num2));`
In the dApp code was this:
`const randomness = solidityKeccak256(["uint256", "uint256"], [num1, num2]);`
This caused different randomness values which caused the UI to show different states than what the contract was actually resolving.
You thought you won but you actually lost 😅 

[dapp-high-roller] Fixes randomness logic in high roller for contract

---

.circleci/config.yml

If `app-name` is not specified it was using `HEROKU_APP_NAME` in env which we set on circleci UI
doc: https://circleci.com/orbs/registry/orb/circleci/heroku

[circleci] Update circleci config with 2 more heroku apps

---

packages/machine/src/models/state-channel.ts

The wrong keys for setting the balances were being used. This fixes it.

[machine] Fix balance keys

---

packages/contracts/truffle-config.js

Since all contracts are upgraded by bot, and we are using waffle instead of truffle for contract build, it's better to remove the compiler version to avoid confusion.

[contracts] remove truffle compiler version to avoid confusion

---

packages/playground/src/components/account/account-exchange/account-exchange.tsx

__Previously on "The Playground"...__
The `isDepositPending` and `isWithdrawalPending` flags were private getters (which can't use the `@State` decorator), so they wouldn't be able to trigger changes to the render if the tunneled properties used to compute its value didn't change.
This PR explicitly uses a combination of `@Watch` + `@State` to make sure we're listening for the changes at the right moment.
*[cue opening theme]*

[playground] For post-deposit, converts pending flags @State(), so they trigger rendering

---

packages/machine/src/protocol/utils/get-channel-from-counterparty.ts

AFAICT `userNeuteredExtendedKeys` is not sorted, so the previous code should not have worked

[machine] sort userNeuteredExtendedKeys in getChannelFromCounterparty

---

packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx

High Roller winner logic was reversed.
The contract was returning correct dice rolls but the UI was putting the winnerRollResult into the LoserRolls :trollface: 
This fixes that. There is also an `isProposing` prop that is passed around in the game. Maybe we should be using this?

[dapp-high-roller] Fix High Roller Winner Player Logic

---

packages/node/src/methods/app-instance/uninstall-virtual/controller.ts
packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/errors.ts

Added it twice because you might call the method while another uninstall request is currently pending in the queue or being executed and have the `beforeExecution` method not catch this.

[node] Add error message on attempt to uninstall already uninstalled app

---

packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-home/apps-list-item/apps-list-item.tsx
packages/playground/src/components/app-home/apps-list/apps-list.tsx
packages/playground/src/components/app-root/app-root.tsx

This should solve the following issues:
- The apps are not blocked on the UI when the channel is not fully collateralized
- fix the dapps on home screen having a `/#` link instead of correct links after the registration & deposit flow is complete

[playground] Fix hash links for dApps if they're not yet available

---

packages/high-roller-bot/src/utils.ts
packages/tic-tac-toe-bot/src/utils.ts

If we get an `"invalid-json"` error then it means the server is down essentially. This happens when the server is restarting and the bot is also restarting at the same time. With this code it pings once every second for 10 seconds until it gets some response. If no response, then it errors.

[bots] Retry getting user on bot startup script

---

packages/playground/src/components/account/account-register/account-register.tsx

It was possible to visit the `/register` screen and trying to register resulted in, obviously, an error in MM.
This fixes the issue by redirecting to `/` if `walletState.metamaskUnlocked==false`

[playground] fix: redirect home from register if mmLocked

---

packages/playground-server/src/db.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/data/account.tsx
packages/playground/src/data/playground-api-client.ts

Fixed the error where your account no longer has a valid state channel in the playground DB

[pg-server, pg] Adds a corrupt waller state UI and delete account button

---

packages/playground-server/src/api.ts
packages/playground-server/src/resources/app/processor.ts

This PR removes the logs for `/heartbeats` and `/apps`, since they're pretty much noise and constantly repeating themselves.

[playground-server] Removes logs for /apps and /heartbeats

---

packages/machine/src/instruction-executor.ts
packages/machine/src/protocol/install-virtual-app.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/setup.ts
packages/machine/src/protocol/take-action.ts
packages/machine/src/protocol/uninstall-virtual-app.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/src/protocol/withdraw-eth.ts
packages/machine/src/types.ts

Long ago, `Context` was used to store intermediate results, the state channel map that is to be mutated, the read-only networkContext, etc. The provider and first message were passed in directly. Since there is no real distinction between the arguments in `Context` and those not, this PR moves the provider and first message into `Context`.

Move arguments to Context

---

packages/cf.js/jest.config.js
packages/machine/jest.config.js
packages/tic-tac-toe-bot/jest.config.js

Due to jest using the vm module (https://github.com/facebook/jest/issues/5163#issuecomment-355509597), certain functions in the BN.js library used by ethers run really slowly under jest without this flag.

[monorepo] add Math to extraGlobals

---

packages/playground-server/package.json
packages/playground-server/src/resources/app/resource.ts
packages/playground-server/src/resources/heartbeat/resource.ts
packages/playground-server/src/resources/matchmaking-request/resource.ts
packages/playground-server/src/resources/multisig-deploy/processor.ts
packages/playground-server/src/resources/multisig-deploy/resource.ts
packages/playground-server/src/resources/session-request/resource.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground-server/src/resources/user/resource.ts
packages/playground-server/test/api.spec.ts
yarn.lock

This PR introduces the following changes required by jsonapi-ts@0.1.17:
- All resources now have a defined schema.
- The UserProcessor now implements an `identify` operation, which is private and non-HTTP mapped, to fetch data for an user who's trying to login. That way, the `get` operation needs no further authorization checks and cannot be spoofed to leak user data.
Resolves #1230.

[playground-server] Updates jsonapi-ts to 0.1.17

---

packages/apps/contracts/CommitRevealApp.sol
packages/apps/contracts/CountingApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/PaymentApp.sol
packages/apps/contracts/TicTacToeApp.sol
yarn.lock

in light of #1208 , all apps are living example of the abstract contract of `CounterfactualApp` and how to directly import and inherent from it.

[contracts] remove unnecessary import

---

packages/tic-tac-toe-bot/test/integration.spec.ts

This import was causing `yarn:lint` to lint the node package as well

[tic-tac-toe-bot] fix bad import

---

packages/machine/test/integration/eth-virtual-app-agreement-commitment.spec.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/integration/make-network-context.ts
packages/machine/test/integration/message-router.ts
packages/machine/test/integration/mininode.ts
packages/machine/test/integration/protocols.spec.ts
packages/machine/test/integration/set-state.spec.ts
packages/machine/test/integration/setup-then-set-state.spec.ts
packages/machine/test/integration/virtual-app-set-state-commitment.spec.ts
packages/node/test/integration/utils.ts
packages/types/src/index.ts

Use the tdr-generated file for deployed addresses instead of reading the artifact's network field

[machine] use tdr in integration test

---

.circleci/config.yml

The name `run-tests` is used for both a workflow and a job; this renames the job to `run-non-playground-tests`

[monorepo] rename run-tests job

---

packages/dapp-high-roller/package.json
packages/playground/package.json
yarn.lock

They seemed to have broken the latest published version
https://github.com/ionic-team/stencil/issues/1464

Revert @stencil/core to 0.18.1-0

---

packages/apps/contracts/CommitRevealApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/TicTacToeApp.sol
packages/contracts/contracts/CounterfactualApp.sol
packages/contracts/contracts/default-apps/ETHBalanceRefundApp.sol
packages/contracts/contracts/default-apps/ETHBucket.sol
packages/contracts/contracts/test-fixtures/ResolveToPay5WeiApp.sol

- delete `revert("not implemented")`s in app definitions which only define a resolve function. It seems that solidity no longer complains if virtual functions are not implemented in the child function.
- change `CounterfactualApp` to be `interface`
- mark CounterfactualApp functions as `external` instead of `public`; required by interfaces and saves a tiny bit of gas

[monorepo] `CounterfactualApp` cleanup

---

packages/cf.js/API_REFERENCE.md
packages/cf.js/src/app-factory.ts
packages/types/src/node.ts

This updates the API doc to refer to the correct identifier used for the Nodes instead of the `Address` type.

[node] Fix identifier reference in API doc

---

packages/contracts/README.md
packages/contracts/networks/42.json
packages/contracts/package.json

This deploys the updated ProxyFactory contract as needed by https://github.com/counterfactual/monorepo/pull/1265

[contracts] Deploy updated ProxyFactory contract

---

packages/node/src/node.ts
packages/playground-server/README.md
packages/playground-server/src/index.ts

This updates the error message for not having a mnemonic set for the playground server to direct the user to be able to set it up.
It also exposes a node's public identifier for easier accessibility to the node's "address".

[node][playground-server] Update error message & expose public identifier

---

packages/node/package.json

During the transition of moving the machine package under the node package, the test script broke, preventing test regexes from being used to filter tests to run.
Now test regex for node tests can be specified via:
```
yarn test:node <regex>
```

[node] Fix node test scripts

---

renovate.json

This dependency isn't 100% respectful of semver, and it introduces breaking changes often.

[monorepo] Asks `renovate` to ignore @ebryn/jsonapi-ts

---

packages/dapp-high-roller/src/components/app-game/app-game.tsx
packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/utils/utils.ts

Add `generateSalt` function from [here](https://github.com/counterfactual/getting-started/blob/8507d9f567d809d957c45e48c148a164b2601d37/src/js/app.js#L337) to utils. Use in `handleRoll` to generate a random salt and add it to the `HighRollerAppState`. Retrieve from state in `onUpdateState`.
resolves #1319

[Dapp High Roller] Generate random numberSalt for commitToHash action

---

packages/node/src/events/propose-install-virtual/operation.ts
packages/node/src/events/propose-install/operation.ts
packages/node/test/global-setup.jest.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/install.spec.ts
packages/node/test/integration/propose-install-virtual.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/node-test-environment.jest.js

There's a bug that's causing the Node to not account for deposits of differing amounts between two participants of a channel.
For example, with a channel A<->B that's funded with 2 ETH (1 ETH from each participant respectively), A initiating an installation of an app for `(A: 0.1 ETH, B: 0 ETH)` would incorrectly leave B's state as `(myDeposit: 0.1 ETH, peerDeposit: 0 ETH)` when it should obviously be `(myDeposit: 0 ETH, peerDeposit: 0.1 ETH)`

[node] Fix setting of deposits for non-matching amounts

---

packages/cf.js/API_REFERENCE.md
packages/dapp-high-roller/src/data/types.ts
packages/high-roller-bot/src/bot.ts
packages/high-roller-bot/src/utils.ts
packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/node.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/node/test/integration/utils.ts
packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/layout/layout-header/header-balance/header-balance.tsx
packages/tic-tac-toe-bot/src/bot.ts
packages/tic-tac-toe-bot/src/utils.ts
packages/types/src/node-protocol.ts
packages/typescript-typings/types/ethers/index.d.ts

This PR changes the return type of the `GetFreeBalance` node RPC method from
```
{
alice: string;
bob: string;
aliceBalance: BigNumber;
bobBalance: BigNumber;
}
``` 
to
```
{
[s: string]: BigNumber;
};
```
The motivation is to a more stable return type so that the ETHBucket contract can be upgraded (e.g. Interpreters, >2-party channels) independently of the consumers of the `GetFreeBalance` RPC method.

[monorepo] change getFreeBalance return type

---

packages/node/test/integration/get-app-instances.spec.ts

- use `A as B`
- use return-type destructuring, similar to commitment unit tests

[node] test cleanup

---

packages/high-roller-bot/package.json
packages/high-roller-bot/src/utils.ts
packages/node/package.json
packages/node/src/node.ts
packages/node/src/utils.ts
packages/playground-server/package.json
packages/playground/package.json
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/src/utils.ts

Previously trying to calculate the ETH free balance address was too cumbersome:
```
fromExtendedKey(node.publicIdentifier).derivePath("0").address
```
This introduces a getter `ethFreeBalanceAddress` that retrieves the above computed address.

[node] Expose ETH free balance address

---

.circleci/config.yml
packages/node/rollup.config.js
packages/playground/src/index.html

As of the inclusion of `loglevel`, the exports weren't properly handled causing the playground to fail to load.
This fixes that along with a few other exports.

[node] Fix exports

---

.circleci/config.yml

This temporarily removes the PG tests from running as no change is being made to the PG.

[playground] Skip PG tests

---

packages/cf.js/API_REFERENCE.md

This adds example strings for the ABI encodings to make it easier to newer developers with understanding how the encoding is supposed to be expressed for an App.

[documentation] Add encoding string examples to the API_REFERENCE

---

packages/types/src/data-types.ts

The `proposed{By,To}Identifier` fields of `AppInstanceInfo` contain node public identifiers, not addresses

[types] use more accurate types

---

.circleci/config.yml

Fixes #1434.
Made an account on Docker Hub and `counterfactual` organization we can re-use.

Move docker image for CI to our image + autobuilding

---

packages/apps/package.json
packages/contracts/networks/3.json
packages/contracts/networks/4.json
packages/contracts/networks/42.json
packages/contracts/package.json
packages/node/package.json
yarn.lock

A couple of contracts (`TwoPartyEthAsLump` and `TwoPartyVirtualEthAsLump`) weren't deployed as part of the [Interpreters PR](github.com/counterfactual/monorepo/pull/1263).
This deploys them and reverts truffle back to a version that makes migrations functional.

[contracts] Deploy new contracts

---

packages/contracts/contracts/libs/LibStaticCall.sol
packages/contracts/contracts/test-fixtures/TestCaller.sol
packages/contracts/test/static-call.spec.ts

These have no forseeable uses AFAICT. The `staticcall_as_bytes` wrapper could still be used for calling `resolve`.

[contracts] delete type-specialized staticcall wrappers

---

packages/contracts/contracts/TwoPartyVirtualEthAsLump.sol
packages/node/src/machine/virtual-app-key.ts
packages/specs/source/protocols/install-virtual-app.md

From the state channels standardization workshop, it seems to me that "direct channel" is more unambiguous than "ledger channel".

[monorepo] rename ledger -> direct

---

packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/take-action.ts
packages/node/src/protocol/uninstall-virtual-app.ts
packages/node/src/protocol/withdraw-eth.ts

We should be extremely explicit about what goes into machine-level protocol messages; these `IO_SENDS` only need to pass and not `params`

[node] only pass protocolExecutionID

---

packages/cf.js/package.json
packages/cf.js/tsconfig.json
packages/dapp-high-roller/tsconfig.json
packages/high-roller-bot/scripts/postinstall.sh
packages/high-roller-bot/tsconfig.json
packages/node-provider/package.json
packages/node-provider/tsconfig.json
packages/node/package.json
packages/node/tsconfig.json
packages/playground-server/tsconfig.json
packages/playground/tsconfig.json
packages/types/package.json
packages/types/tsconfig.json

1. Uses "build mode" in replacement of "project mode" everywhere (i.e., uses `-b`)
2. Changes `types` to use the `composite` flag
3. Replaces `tsconfig.json` with `.` when that is implicit

[repo] Add typescript references for types package

---

packages/contracts/contracts/StateChannelTransaction.sol
packages/contracts/contracts/interfaces/Interpreter.sol
packages/contracts/contracts/interpreters/ETHInterpreter.sol
packages/contracts/contracts/interpreters/TwoPartyEthAsLump.sol

Makes it more explicit based on shared terminology

Rename interpret to interpretOutcomeAndExecuteEffect

---

packages/contracts/contracts/StateChannelTransaction.sol
packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MixinSetOutcome.sol
packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/contracts/test/utils/index.ts
packages/node/src/ethereum/utils/encodings.ts
packages/node/src/models/app-instance.ts
packages/node/test/machine/unit/ethereum/eth-virtual-app-agreement-commitment.spec.ts
packages/node/test/machine/unit/ethereum/install-commitment.spec.ts
packages/node/test/machine/unit/ethereum/set-state-commitment.spec.ts
packages/node/test/machine/unit/ethereum/uninstall-commitment.spec.ts
packages/node/test/machine/unit/ethereum/virtual-app-set-state-commitment.spec.ts
packages/specs/source/adjudication-layer.md
packages/specs/source/protocols/update.md
packages/types/src/app-instance.ts

We needed `termsHash` before because the `resolve` function used it in its arguments (because we wanted to allow an application to use `terms.limit`). Now, however, the interpreter is a higher-order concept and so we no longer need this state.

Remove interpreterHash

---

packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinCancelChallenge.sol
packages/contracts/contracts/mixins/MixinRespondToChallenge.sol
packages/contracts/contracts/mixins/MixinSetOutcome.sol
packages/contracts/contracts/mixins/MixinSetState.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/contracts/mixins/MixinVirtualAppSetState.sol
packages/contracts/test/app-registry-dispute.spec.ts
packages/contracts/test/app-registry.spec.ts
packages/contracts/test/utils/index.ts
packages/specs/source/adjudication-layer.md
packages/types/src/simple-types.ts

Generally we've agreed on this new naming, so let's use the word challenge instead of dispute.

Rename dispute to challenge everywhere

---

.circleci/images/build/Dockerfile

Docker Hub autobuilds from the `master` branch so this is needed for the https://github.com/counterfactual/monorepo/pull/1544 build to succeed.
We need it because in that PR it requires Node > 10.5 and the new docker image has that.
Here is the error this should fix:
```bash
#!/bin/bash -eo pipefail
yarn --frozen-lockfile
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.0.6: The platform "linux" is incompatible with this module.
info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.6: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || >=11.0.0". Got "10.4.0"
info fsevents@1.2.9: The platform "linux" …
```

Update Dockerfile of CircleCI Node environment

---

.circleci/images/build/Dockerfile

This `node` is still at 10.4.0 but `/usr/bin/node` is 10.15.3 as required.

Remove /usr/local/bin/node in Docker container

---

packages/postgresql-node-connector/package.json

https://github.com/counterfactual/monorepo/pull/1586 missed scoping the package name.
As a side note: This package has been published with this updated name: https://www.npmjs.com/package/@counterfactual/postgresql-node-connector

[postgres-connector] Include org scope in package name

---

packages/playground-server/scripts/postinstall.sh

For some reason `playground-server-staging` builds are failing on Heroku
```
npm ERR! path /tmp/build_7640c419819b5fe55ff7ba526690ab79/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /tmp/build_7640c419819b5fe55ff7ba526690ab79/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /tmp/build_7640c419819b5fe55ff7ba526690ab79/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.irycY/_logs/2019-05-31T16_23_00_099Z-debug.log
```

Attempt to delete a rambunctious file

---

packages/playground-server/package.json
packages/playground-server/scripts/heroku-postbuild.sh
packages/playground-server/scripts/postinstall.sh

When running `yarn --focus --production` in the `playground` package I encountered an issue where the `postinstall` script of the `playground-server` package.
```
error /Users/liam/src/code/monorepo/node_modules/@counterfactual/playground-server, /Users/liam/src/co
de/monorepo/packages/playground/node_modules/@counterfactual/playground-server: Command failed.
Exit code: 127
Command: sh ./scripts/postinstall.sh
Arguments: 
Directory: /Users/liam/src/code/monorepo/packages/playground/node_modules/@counterfactual/playground-s
```
I don't fully know why this package is even involved

Split up heroku postbuild script in playground-server

---

package.json

In response to this thing I saw
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

Specify node engine in package.json

---

packages/firebase-client/package.json
packages/firebase-server/package.json
packages/node/package.json
packages/playground-server/package.json

We do need another script to verify the dist exists before publishing happens but this is a quick fix to get around consumers being blocked.

[firebase-client] Bump package to include dist

---

packages/apps/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/contracts/package.json
packages/dapp-high-roller/package.json
packages/dapp-tic-tac-toe/package.json
packages/firebase-client/package.json
packages/firebase-server/package.json
packages/high-roller-bot/package.json
packages/node-provider/package.json
packages/node/package.json
packages/playground-server/package.json
packages/playground/package.json
packages/postgresql-node-connector/package.json
packages/tic-tac-toe-bot/package.json
packages/types/package.json
packages/typescript-typings/package.json

Useful when one package is being pulled in a deployment context like Heroku

Specify yarn and node engines everywhere

---

.circleci/images/build/Dockerfile

Has to happen before https://github.com/counterfactual/monorepo/pull/1628 so the image gets built on `master` merge.

Update yarn to 1.12.3 on Dockerfile (needs to happen first)

---

packages/apps/contracts/HighRollerApp.sol
packages/dapp-tic-tac-toe/src/Game.jsx
packages/node/src/protocol/install.ts

TicTacToe client logic depended on the `players` variable in the `AppState` of the `TicTacToe`. However, we could not rely on this anymore since the Interpreter PR (#1263) removed this variable from the contract. Now that it is gone, we rely on the `beneficiaries` field of the `AppInstance` that @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll added. This field is temporary (since it is hard coded to a specific interpreter but happens to be getting written to in the Install Protocol (see [1]).
Also, separately, the `interpreterParams` for the `TwoPartyEthAsLump.sol` interpreter were being incorrectly set, this fixes that.
[1] https://github.com/counterfactual/monorepo/blob/6fe51b12c5dc1b4c54cb794a393c052488d1f472/packages/node/src/protocol/install.ts#L143

Fix players variable reliance of TicTacToe app code

---

packages/cf-wallet.js/src/app-instance.ts
packages/cf-wallet.js/test/provider.spec.ts
packages/cf.js/API_REFERENCE.md
packages/cf.js/src/app-factory.ts
packages/cf.js/src/app-instance.ts
packages/cf.js/test/app-factory.spec.ts
packages/cf.js/test/app-instance.spec.ts
packages/cf.js/test/provider.spec.ts
packages/dapp-high-roller/src/data/mock-app-instance.ts
packages/dapp-high-roller/src/data/types.ts
packages/dapp-tic-tac-toe/src/MockNodeProvider.js
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/utils.ts
packages/playground/src/components/node-listener/dialogs/propose-install/dialog-propose-install.tsx
packages/playground/src/components/node-listener/node-listener.tsx
packages/tic-tac-toe-bot/test/integration.spec.ts
packages/types/src/data-types.ts
packages/types/src/node.ts

`appId` is an outdated name. `appDefinition` is the more clear and commonly used term to refer to the address of a contract.

Remove variable name appId, replace w/ appDefinition

---

packages/high-roller-bot/yarn.lock
packages/playground-server/yarn.lock
packages/tic-tac-toe-bot/yarn.lock
yarn.lock

[Last merge](https://github.com/counterfactual/monorepo/pull/1618) failed at the heroku deployment phase due to outdated lock file. 
```
remote: -----> Installing dependencies        
remote:        Installing node modules (yarn.lock)        
remote:        yarn install v1.12.3        
remote:        [1/4] Resolving packages...        
remote:        error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.        
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.        
remote: 
remote: -----> Build failed        
remote: 
remote:  !     Outdated Yarn lockfile        
```

[monorepo] Update lock file

---

packages/cf-wallet.js/src/app-instance.ts
packages/cf.js/src/app-instance.ts
packages/dapp-tic-tac-toe/src/Game.jsx
packages/node/src/ethereum/two-party-virtual-eth-as-lump-commitment.ts
packages/node/src/models/app-instance.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/models/state-channel.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/utils/get-outcome-increments.ts
packages/node/src/protocol/withdraw-eth.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/two-party-virtual-eth-as-lump-commitment.spec.ts
packages/node/test/machine/integration/virtual-app-set-state-commitment.spec.ts
packages/node/test/machine/unit/ethereum/virtual-app-set-state-commitment.spec.ts
packages/node/test/machine/unit/models/app-instance/app-instance.spec.ts
packages/node/test/unit/utils.ts
packages/types/src/data-types.ts

These fields were not added in the Interpreter PR #1263 (cc: @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll for reference) to the clientside API wrapper class for an `AppInstance` inside `cf.js` and `cf-wallet.js`. This adds them.
**Field rename**
- `limitOrTotal` was `amount` if TwoPartyOutcome interpreter type or `limit` if ETHTransfer interpreter type.
- `beneficiaries` was `playerAddrs` if TwoPartyOutcome else meaningless (but set to `[0x0, 0x0]`)

Add limitOrTotal and beneficiaries to client API wrapper class (also rename them to be explicit)

---

packages/node/src/events/channel-created/controller.ts

This event was deprecated some time ago but in the #1613 branch it is causing problems.

Remove deprecated event handler being misfired

---

.gitignore
packages/postgresql-node-connector/package.json
packages/postgresql-node-connector/src/index.ts

The `node_records` table creation query had a line that sets the owner to a hard-coded "postgres".
I replaced "postgres" with the username provided by the configuration.
none
^ idk what this means but this change fixed a bug while deploying `ConnextProject/indra-v2` so there's that

postgresql-node-connector: Fix hard-coded username

---

packages/apps/contracts/ETHUnidirectionalTransferApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/TicTacToeApp.sol
packages/cf.js/src/app-factory.ts
packages/cf.js/test/app-factory.spec.ts
packages/cf.js/test/provider.spec.ts
packages/contracts/contracts/default-apps/ETHBalanceRefundApp.sol
packages/contracts/contracts/default-apps/ETHBucket.sol
packages/contracts/contracts/interfaces/CounterfactualApp.sol
packages/contracts/contracts/test-fixtures/AppWithAction.sol
packages/contracts/contracts/test-fixtures/FixedTwoPartyOutcomeApp.sol
packages/node/src/machine/types.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/utils/get-outcome-increments.ts
packages/node/test/integration/take-action.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/machine/integration/protocols.spec.ts
packages/node/test/unit/utils.ts
packages/types/src/node.ts

This PR removes `outcomeType` as a mandatory field on `CounterfactualApp`.
Outstanding issues with the whole thing we will address in future PRs:
- Virtual apps still have a hard-coded requirement of `TwoPartyFixedOutcome`
- `interpreterAddress` and `interpreterParameters` are still hard-coded based on `outcomeType` in the `InstallParams`, but ought to be in the `InstallParams`

Remove outcomeType solidity function in favour of InstallParams field

---

packages/playground/src/components/account/account-exchange/account-exchange.tsx

`this.ethFreeBalanceWei` could be undefined here.
That is why there is `const ethFreeBalanceWei = this.ethFreeBalanceWei || Zero;` above.
It seems the exchange page was broken for a while :)
Caused by: #1369

[Playground] Fix ethFreeBalanceWei was using incorrect var

---

packages/apps/contracts/ETHUnidirectionalTransferApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/TicTacToeApp.sol
packages/contracts/contracts/default-apps/ETHBalanceRefundApp.sol
packages/contracts/contracts/default-apps/ETHBucket.sol
packages/contracts/contracts/interfaces/Interpreter.sol
packages/contracts/contracts/interpreters/ETHInterpreter.sol
packages/contracts/contracts/interpreters/TwoPartyEthAsLump.sol
packages/contracts/contracts/libs/LibOutcome.sol
packages/contracts/contracts/test-fixtures/AppWithAction.sol
packages/contracts/contracts/test-fixtures/FixedTwoPartyOutcomeApp.sol

Outcome type is a very different concept than Interpreter but the data structure definitions for common outcome types was very coupled to the contract code and namespace of interpreters. This explicitly de-couples them.

Create LibOutcome for code clarity

---

yarn.lock

This fixes the current problem with building from the root.
```
yarn build
yarn run v1.12.3
$ sh build.sh
⚙️  Building package: types                                                                                                                                                                                                                  
$ tsc -b . && rollup -c
src/node.ts:2:10 - error TS2305: Module '"../../../../../../../Users/nima/Counterfactual/monorepo/node_modules/rpc-server/dist"' has no exported member 'JsonRpcNotification'.
2 import { JsonRpcNotification, JsonRpcResponse, Rpc } from "rpc-server";
~~~~~~~~~~~~~~~~~~~
Found 1 error.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed …
```

[monorepo] Regenerate yarn lock

---

packages/playground-server/package.json
packages/playground-server/registry.json

The Playground Server registry is pointing to `*-staging` subdomains for the dApps, which are highly unstable due to most recent refactors and changes to the Node, making `playground.counterfactual.com` a bit useless, since no games can be played.
This PR removes TTT from the apps list, since we do not have a frozen version of it, and points High Roller to the production version.

[Hotfix] Serve only High Roller in Production Playground

---

packages/contracts/contracts/libs/LibAppCaller.sol
packages/contracts/contracts/mixins/MixinRespondToChallenge.sol
packages/contracts/contracts/mixins/MixinSetOutcome.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/contracts/mixins/MixinVirtualAppSetState.sol

Since this piece of code does not use any storage from the challenge registry, it should be a library

make MAppCaller a library

---

packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/contracts/mixins/MixinVirtualAppSetState.sol
packages/node/src/ethereum/virtual-app-set-state-commitment.ts
packages/node/test/machine/integration/virtual-app-set-state-commitment.spec.ts
packages/node/test/unit/utils.ts

- fix some revert messages in solidity
- use proper case for `appversionNumber` 
- make the target app instance in the integration test not use the free balance app state

[monorepo] cleanup related to virtualAppSetState

---

packages/contracts/contracts/ConditionalTransactionDelegateTarget.sol
packages/node/src/ethereum/setup-commitment.ts
packages/node/test/machine/unit/ethereum/setup-commitment.spec.ts

This PR makes the free balance app instance permanently installed. It does this by adding a `executeEffectOfFreeBalance` delegate target which is similar to `executeEffectOfInterpretedAppOutcome` but without uninstall key and with the limit parameter specialized.
Motivation: This is part of work to make the active apps dispute mechanism go through the free balance app instance. The full set of contract changes (without client changes) to do this can be seen at https://github.com/counterfactual/monorepo/pull/1774 .

[contracts] make free balance not uninstallable

---

packages/node/src/events/install/controller.ts
packages/node/src/machine/instruction-executor.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/uninstall-virtual/operation.ts
packages/node/src/methods/app-instance/uninstall/operation.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/methods/state-channel/withdraw/operation.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/protocols.spec.ts
packages/node/test/machine/integration/virtual-app-install.spec.ts
packages/node/test/unit/install.spec.ts

This PR introduces an `initiateProtocol` function that replaces the `run<ProtocolName>Protocol` functions, except for the `runSetupProtocol` function. `initiateProtocol` takes an additional argument specifying the protocol, and ensures that the params argument correspond to the protocol argument.

[node] introduce initiateProtocol

---

packages/chain/package.json
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/utils.ts

This replaces a global queue topic `instructionExecutorCoreQueue` with topics relevant to the protocol being executed.

[node] Update protocol message handling to queue on different topics

---

packages/contracts/contracts/ConditionalTransactionDelegateTarget.sol

This PR replaces the `CoinTransferParams` struct defined in `ConditionalTransactionDelegateTarget.sol` and replaces it with the ``Params` struct from `CoinTransferETHInterpreter`. Reasons:
- `CoinTransfer` is an outcome type, not a param type
- The structs are the same

[contracts] remove CoinTransferParams

---

packages/types/src/data-types.ts

This type was added together with the solidity enum field, but the later was eventually deleted

[types] remove TWO_PARTY_DYNAMIC_OUTCOME

---

packages/cf.js/test/app-factory.spec.ts
packages/node/src/machine/types.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/models/app-instance.ts
packages/node/src/models/free-balance.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/utils/get-outcome-increments.ts
packages/node/src/protocol/withdraw.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/install-virtual.spec.ts
packages/node/test/machine/integration/protocols.spec.ts
packages/node/test/machine/integration/virtual-app-set-state-commitment.spec.ts
packages/node/test/machine/unit/ethereum/virtual-app-set-state-commitment.spec.ts
packages/node/test/machine/unit/models/app-instance/app-instance.spec.ts
packages/node/test/unit/utils.ts
packages/types/src/data-types.ts
tsconfig.json

- add an explicit `outcomeType` field to the app instance model
- split up the `COIN_TRANSFER` outcome type to accurately reflect actual outcome types

[node] add explicit outcomeType

---

packages/wallet-ui/src/App.tsx
packages/wallet-ui/src/components/account/account-context/AccountContext.spec.tsx
packages/wallet-ui/src/components/account/account-context/AccountContext.tsx
packages/wallet-ui/src/components/form/form-button/FormButton.tsx
packages/wallet-ui/src/components/form/form-input/FormInput.tsx
packages/wallet-ui/src/pages/account-deposit/AccountDeposit.spec.tsx
packages/wallet-ui/src/pages/account-deposit/AccountDeposit.tsx
packages/wallet-ui/src/pages/account-registration/AccountRegistration.spec.tsx
packages/wallet-ui/src/pages/account-registration/AccountRegistration.tsx
packages/wallet-ui/src/pages/welcome/Welcome.spec.tsx
packages/wallet-ui/src/pages/welcome/Welcome.tsx
packages/wallet-ui/src/store/wallet/wallet.ts
packages/wallet-ui/src/utils/hub-api-client.ts

This PR fixes several errors found in the Wallet-UI by @joelalejandro, and another one that could crash the app when the account creation function call failed.
It also leaves the deposit screen ready to handle errors for when we manage to make deposits work. 
- closes #1952 
- closes #1958 
- refactors #1954 (doesn't improve much, but at least the error messages and codes are extracted from the class)
- closes #1951

[Wallet-UI] Various small fixes

---

packages/apps/package.json
packages/cf-wallet.js/package.json
packages/cf-wallet.js/src/provider.ts
packages/cf.js/package.json
packages/chain/package.json
packages/contracts/package.json
packages/firebase-client/package.json
packages/high-roller-bot/package.json
packages/high-roller-bot/src/utils.ts
packages/node-provider/package.json
packages/node/README.md
packages/node/package.json
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/node.ts
packages/node/src/request-handler.ts
packages/node/src/rpc-router.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/playground/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/src/utils.ts
packages/types/package.json
packages/types/src/node.ts

This removes the `notifyCounterparty` parameter on the deposit API and explicitly expects the Node consumer to setup a handler attached to the `DEPOSIT_CONFIRMED` event.

[node] Remove nofiyCounterparty param

---

packages/apps/package.json
packages/chain/package.json
packages/contracts/contracts/interpreters/TwoPartyFixedOutcomeETHInterpreter.sol
packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MChallengeRegistryCore.sol
packages/contracts/contracts/mixins/MixinCancelChallenge.sol
packages/contracts/contracts/mixins/MixinSetState.sol
packages/contracts/networks/3.json
packages/contracts/networks/4.json
packages/contracts/networks/42.json
packages/contracts/package.json
packages/contracts/test/challenge-registry-dispute.spec.ts
packages/contracts/test/challenge-registry.spec.ts
packages/contracts/test/utils/index.ts
packages/high-roller-bot/package.json
packages/node/package.json
packages/node/src/ethereum/utils/app-identity.ts
packages/node/src/ethereum/utils/encodings.ts
packages/node/src/models/app-instance.ts
packages/node/test/machine/integration/install-virtual.spec.ts
packages/node/test/machine/unit/ethereum/set-state-commitment.spec.ts
packages/simple-hub-server/package.json
packages/specs/source/adjudication-layer.md
packages/specs/source/protocols/update.md
packages/tic-tac-toe-bot/package.json
packages/types/src/app-instance.ts

The owner property is used for:
1. Added uniqueness on a per `StateChannel` basis of an `AppInstance`
2. Allowing `CALL`s made by a multisignature wallet to override the `signingKeys` property on the adjudicator
This PR removes the ability for both (1) and (2) at the moment.
This means uniqueness for an `AppInstance` is only obtained by unique `signingKeys`, `appDefinition`, and `defaultTimeout` as of the current state of this pull request. It becomes the clients responsibility to never install an `AppInstance` that re-uses all three variables.
Because there is a possibility that `signingKeys` _may_ want to be re-used (although not clear), a new field could be added to the `AppIdentity` called `nonce` or `uniqueKey` or something like this, but it's unclear if that is needed.

Remove  the `owner` property on an AppIdentity

---

packages/node/README.md
packages/node/docs/diagram.md

The diagrams were broken with the proposed `mermaid-diagram` extension for Chrome due to whitespace and aliasing problems.
I added an extra extension called `mermaid` as a possible choice to read the diagrams and fixed some syntax errors.
Resolves #1993.

[node] [documentation] Fixes diagrams' readibility for Chrome extensions, links document from the README

---

packages/node/test/integration/uninstall.spec.ts
packages/node/test/integration/utils.ts

This adds tests for using the Node to exercise the different outcomes that are possible with the `TwoPartyFixedOutcome` outcome type.

[node] More rigorous testing of the TwoPartyFixedOutcome

---

packages/high-roller-bot/package.json
packages/high-roller-bot/src/utils.ts
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/src/utils.ts

`ethFreeBalanceAddress` was renamed to `freeBalanceAddress ` This broke the bots in a previous PR.
Broken by: #1984

[Bots] fix: Use correct freeBalanceAddress after rename.

---

tsconfig.json

Allows "jump to source" for references, e.g., `@counterfactual/types`.

Add declarationMap

---

package.json
packages/wallet-ui/package.json
packages/wallet-ui/src/store/channels/channels.mock.ts
packages/wallet-ui/src/store/user/user.mock.ts
packages/wallet-ui/src/store/user/user.ts
packages/wallet-ui/src/store/wallet/wallet.ts
packages/wallet-ui/src/utils/counterfactual.ts
packages/wallet-ui/src/utils/testSelector.ts

```sh
yarn run:wallet
yarn run:dapps
yarn run:bots
```
```sh
yarn lint
yarn lint:fix
```
Resolves #2027.
Resolves #2028.

[monorepo] [wallet-ui] Adds new run-scripts and lint-scripts for Wallet UI

---

packages/node/src/utils.ts

Fails if any value in the object is undefined, just added a check in the function to look for this case.

[node] check undefined

---

packages/node/src/deferred.ts
packages/node/test/machine/integration/message-router.ts
packages/node/test/machine/integration/protocols.spec.ts
packages/node/test/machine/integration/protocols2.spec.ts

Currently there is a bug in the mininode test harness. Spec files like `protocols.spec.ts` have a pointer to a single IE which they use to initiate protocols, and the outcome of the protocol initiated is awaited, hence errors are caught. However, initiating protocols causes other mininodes to receive messages and hence run protocols as well, but the spec file did not have a pointer to those outcomes. This bug can be reproduced by throwing an error after this line. https://github.com/counterfactual/monorepo/blob/aa3a7b5f28f1c1eb2a561b71cd9179f9b14b8dda/packages/node/src/protocol/setup.ts#L99
This PR fixes this bug.

[node] catch all failing IEs in mininode tests

---

packages/node/src/models/state-channel.ts

This PR creates a `build` method on StateChannel that returns a new copy with selected fields overridden. It also splits out the functions `removeActiveApp` and `incrementFreeBalance`.

[node] use builder pattern

---

packages/apps/test/high-roller-app.spec.ts
packages/apps/test/nim.spec.ts
packages/apps/test/tictactoe.spec.ts
packages/apps/test/unidirectional-transfer-app.spec.ts
packages/cf.js/src/app-factory.ts
packages/cf.js/src/app-instance.ts
packages/cf.js/src/types/events.ts
packages/contracts/test/challenge-registry-dispute.spec.ts
packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/data/mock-app-instance.ts
packages/dapp-high-roller/src/data/types.ts
packages/node/README.md
packages/node/src/machine/types.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/models/app-instance.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/models/state-channel.ts
packages/node/src/store.ts
packages/node/test/integration/tic-tac-toe.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/utils.ts
packages/specs/source/protocols/install-virtual-app.md
packages/types/src/data-types.ts
packages/types/src/index.ts
packages/types/src/node.ts
packages/types/src/simple-types.ts

This allows app states to be primitive types (e.g. numbers)

[monorepo] replace SolidityABIEncoderV2Type with SolidityValueType

---

packages/greenboard/package.json

It doesn't make any sense to publish this as a package, so this PR adds a no-op script to prevent further unwanted publishing :)

[greenboard] Prevents publishing @counterfactual/greenboard

---

packages/node/src/protocol/utils/get-outcome-increments.ts

This function was returning something that was not a `TokenIndexedCoinTransferMap`.
Tested in #2068

[node] fix bug in handleMultiAssetMultiPartyCoinTransfer

---

packages/node/src/models/app-instance.ts
packages/node/src/models/free-balance.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/models/state-channel.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/withdraw.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/install-virtual.spec.ts
packages/node/test/machine/unit/models/app-instance/app-instance.spec.ts
packages/node/test/machine/unit/models/state-channel/setup-channel.spec.ts
packages/node/test/unit/utils.ts

This field is never read; we always use the containing state channel's multisig address instead

[node] remove AppInstance::multisigAddress

---

packages/wallet-ui/src/App.tsx
packages/wallet-ui/src/components/form/form-input/FormInput.tsx
packages/wallet-ui/src/pages/account-deposit/AccountDeposit.tsx
packages/wallet-ui/src/pages/account-withdraw/AccountWithdraw.tsx
packages/wallet-ui/src/store/types.ts
packages/wallet-ui/src/store/wallet/wallet.ts
packages/wallet-ui/src/utils/nodeTokenClient.ts

This PR adds a getter of a list of tokens to use in the wallet-ui.
Currently we use the [MyEtherWallet/ethereum-lists](https://github.com/MyEtherWallet/ethereum-lists), but through a cdn (jsdelivr) e.g [the kovan list of tokens](https://cdn.jsdelivr.net/gh/MyEtherWallet/ethereum-lists/dist/tokens/kov/tokens-kov.min.json).
It also detects the currently selected MM network (I only added support for the non-custom ones).
references #1955

[wallet-ui] Node Tokens list getter and selector

---

packages/high-roller-bot/.env-cmdrc

Fixes typo introduced in #2097.

[high-roller-bot] Fixes typo in .env-cmdrc

---

packages/high-roller-bot/package.json
packages/node/package.json
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/methods/app-instance/uninstall-virtual/controller.ts
packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/controller.ts
packages/node/src/methods/queued-execution.ts
packages/node/test/integration/uninstall-virtual.spec.ts
packages/node/test/integration/uninstall-with-postgres.spec.ts
packages/node/test/integration/uninstall.spec.ts
packages/node/test/integration/utils.ts
packages/playground/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

Concurrency fixes:
1. Install virtual app now has queuing. It did not before.
2. Uninstall virtual app now queues on both channels with counterparties, not just one.
3. Update and take action now queues on app instance identity hash, not multisig address

Handle asymmetric event emission + better concurrency handling

---

e2e-prepare.sh

Using `nvm` to build with the exact version of Node/Yarn that Metamask requires is not working due to `nvm` not being able to persist the version change in a subshell:
```bash
Found '/home/joel/Projects/counterfactual/.nvmrc' with version <v10.15.3>
Now using node v10.15.3 (npm v6.10.2)
(6/7) Installing Metamask dependencies and building extension...
/tmp/metamask-extension ~/Projects/counterfactual
Running node v10.16.0 (npm v6.10.2)
[1/5] Validating package.json...
error metamask-crx@0.0.0: The engine "node" is incompatible with this module. Expected version "^10.16.0". Got "10.15.3"
error metamask-crx@0.0.0: The engine "yarn" is incompatible with this module. Expected version "^1.16.0". Got "1.12.3"
error Found incompatible module
```
Since there's no significant difference between …

[testing] Removes usage of nvm in test:e2e:setup

---

packages/apps/package.json

Output networks folder in apps package.
Dapp Tic Tac Toe depends on this.
In the process of extracting the dapps into their own repo I found that building the dapp fails.
#1956

[apps] Output networks folder in apps package

---

packages/cf-adjudicator-contracts/contracts/libs/LibStateChannelApp.sol

Harden `verifySignatures` by requiring the number of signers matches the number of signatures.

Add check to compare signatures and signer lengths

---

packages/node/docs/source/introduction.md

Add a heading to introduction.md so that toctree parses it correctly

[node-docs] fix heading

---

packages/node-provider/package.json
packages/node-provider/src/index.ts
packages/node-provider/src/node-provider-ethereum.ts
packages/node-provider/src/types.ts
packages/node-provider/test/unit/node-provider-ethereum.spec.ts
packages/node-provider/test/utils/ethereum-mock.ts
packages/node-provider/tsconfig.json
yarn.lock

This is an extraction + enhancement PR based on #1001.
It'll add the `NodeProviderEthereum` class to the `NodeProvider` package, as per @Alonski's original commits, plus adding some better types + unit tests for the new class.

[node-provider] Adds NodeProviderEthereum

---

packages/node/docs/source/api.md
packages/node/src/ethereum/utils/free-balance-app.ts
packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/methods/app-instance/get-token-indexed-free-balances/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/errors.ts
packages/node/src/methods/state-channel/withdraw/controller.ts
packages/node/src/models/free-balance.ts
packages/node/src/models/state-channel.ts
packages/node/test/integration/utils.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/install-virtual.spec.ts
packages/node/test/machine/integration/protocols/test-runner.ts
packages/node/test/machine/integration/set-state.spec.ts
packages/node/test/machine/integration/setup-then-set-state.spec.ts
packages/node/test/machine/unit/ethereum/conditional-transaction-commitment.spec.ts
packages/node/test/machine/unit/models/state-channel/install.spec.ts
packages/node/test/machine/unit/models/state-channel/setup-channel.spec.ts
packages/node/test/machine/unit/models/state-channel/uninstall-app.spec.ts
packages/node/test/unit/install.spec.ts

Previously, the helper file `free-balance.ts` exported 6 data structures and 5 functions:
- `FreeBalanceState`
- `FreeBalanceStateJSON`
- `CoinTransfer`
- `CoinTransferJSON`
- `CoinTransferMap`
- `TokenIndexedCoinTransferMap`
- `getBalancesFromFreeBalanceAppInstance`
- `deserializeFreeBalanceState`
-  `serializeFreeBalanceState`
- `convertCoinTransfersMapToCoinTransfers` 
- `convertCoinTransfersToCoinTransfersMap`
This PR creates a new class, `FreeBalanceClass`, with a smaller conversion API - it has 1 method each to convert to and from from an `AppInstance`, and no other methods should be used for conversion. This allows us to de-export most of the data structures and conversion functions listed above.

[node] Replace `free-balance` API with `FreeBalanceClass`

---

packages/node/package.json
packages/node/rollup.config.js
yarn.lock

This adds Babel along with @babel/plugin-proposal-object-rest-spread to Node so that Rollup transpiles the code.
Object rest spread was causing issues in MM build script.

[node] feat: Add babel to Node to transpile object rest spread

---

packages/node/src/machine/instruction-executor.ts
packages/node/src/machine/types.ts
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/setup.ts
packages/node/src/protocol/take-action.ts
packages/node/src/protocol/uninstall-virtual-app.ts
packages/node/src/protocol/uninstall.ts
packages/node/src/protocol/update.ts
packages/node/src/protocol/withdraw.ts

`ProtocolMessage` had two issues:
- `signature{1,2,3,4}` are not meaningful labels used by the spec
- the install-virtual-app protocol was misusing one of the signatures to pass data
This PR fixes both issues by creating a `customData` field with arbitrary keys allowed and mechanically moving `signature{1,2,3,4}` into it. A follow-up PR will give the signatures better names.

[node] add customData field to ProtocolMessage

---

packages/node/package.json
packages/simple-hub-server/package.json

heroku is reject pushes, because building `simple-hub-server` from scratch fails, because that uses `@counterfactual/node` from npm and the changes in #2183 are not on npm, because #2183 did not bump node version

[node] bump version

---

packages/node/src/machine/xkeys.ts

Don't recompute keys from xpubs any more than needed, cache result the first time then use that again later

[node] cache xkeyKthHDNode

---

packages/cf-funding-protocol-contracts/waffle.js
packages/node/src/methods/state-channel/create/controller.ts

[contracts] make ProxyFactory build reproducible across machines

---

.circleci/config.yml
package.json
packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/firebase-server/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json
packages/typescript-typings/package.json
yarn.lock

Reverts commit `d421345e4fdcd8d639a225ac8b906f9dae92b026`
This is a temporary revert to allow release of new packages. A follow up PR will bump the yarn engine correctly without causing the below errors to appear.
1. 
```
$ yarn
yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning Pattern ["ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git"] is trying to unpack in the same destination "/Users/nima/Library/Caches/Yarn/v4/npm-ethereumjs-abi-0.6.7-8431eab7b3384e65e8126a4602520b78031666fb/node_modules/ethereumjs-abi" as pattern ["ethereumjs-abi@0.6.7"]. This could result in non-deterministic behavior, skipping.
error @counterfactual/cf.js@0.2.4: The engine "yarn" is incompatible with this module. …
```

Revert "Bulk dependencies update #2231"

---

packages/apps/waffle.js
packages/cf-adjudicator-contracts/waffle.js
packages/cf-funding-protocol-contracts/waffle.js
waffle.js

This moves the waffle config to a single location in the root of the repo for relevant packages to inherit from.

[contracts] DRY waffle config

---

packages/node/src/api.ts
packages/node/src/methods/app-instance/get-all/controller.ts
packages/node/src/methods/app-instance/get-app-instance/controller.ts
packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/methods/app-instance/get-state/controller.ts
packages/node/src/methods/app-instance/get-token-indexed-free-balances/controller.ts
packages/node/src/methods/app-instance/install-virtual/controller.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/uninstall-virtual/controller.ts
packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/proposed-app-instance/get-all/controller.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/get-state-deposit-holder-address/controller.ts
packages/node/src/methods/state-channel/get/controller.ts
packages/node/src/methods/state-channel/withdraw-commitment/controller.ts
packages/node/src/methods/state-channel/withdraw/controller.ts
packages/types/src/node.ts

This PR deregisters most "legacy RPC endpoints" (i.e. that use the old routing mechanism)

[node] remove unused legacy RPC endpoints

---

packages/cf-funding-protocol-contracts/manual-deploy.js
packages/cf-funding-protocol-contracts/networks/42.json
packages/node/package.json
packages/simple-hub-server/package.json

Redeploys the `ProxyFactory` contract to ensure the deployed contract is using the same bytecode  for the `Proxy` as is being used to calculate the create2 address for a multisig deployment.
Resolves issue https://github.com/counterfactual/monorepo/issues/2275

[contracts] Redeploy ProxyFactory contract

---

packages/cf-funding-protocol-contracts/manual-deploy.js
packages/cf-funding-protocol-contracts/networks/1.json
packages/cf-funding-protocol-contracts/networks/4.json
packages/cf-funding-protocol-contracts/package.json
packages/local-ganache-server/package.json
packages/node/package.json
packages/simple-hub-server/package.json

Deploys new contracts for `ProxyFactory` on Rinkeby and Mainnet.
Bumps `@cf/contracts`.
Bumps `@cf/node`.

Bump node version and deploy contracts

---

packages/node/src/methods/queued-execution.ts
packages/node/test/integration/install-concurrent-virtual.spec.ts
packages/node/test/integration/utils.ts

In `queued-execution.ts` there were two for loops. The first was intended to add the closure to the list of queued up closures to be executed. The second was to await on each one. Awaiting on each one is safe because there is a cache on the actual closure that ensures the actual method implementation only runs once.
The flaw was that in the second for loop, it was not awaiting on the list that included the updated closures but rather the initial list which did not include it.
This issue manifested itself when you ran two back-to-back (within the same second) requests to the `node` whereby two calls to `getShardedQueue` happened before the for loop that included `queue.add` finished executing per queue.

[node] Fix incorrectly implemented queuing logic

---

packages/node/package.json
packages/simple-hub-server/package.json

0.2.72 includes:
Fix incorrectly implemented queuing logic (#2336)
Correctly queue proposals received (#2335)
Remove unnecessary helper function (#2333)
Only touch DB for responding on virtual proposals (#2332)
Simplify test utility function (#2331)

Bump node version

---

packages/node/src/methods/queued-execution.ts
packages/node/src/process-queue.ts
packages/node/test/integration/connext-issue.spec.ts
packages/node/test/unit/queued-execution.spec.ts

I _believe_ this is doing the functionality that has been intended by Layne's changes in #2348 correctly. I added a test for a single queue scenario to verify. I'm observing that the `connext-issue.spec.ts` test is failing, though. So for now this is a draft.
**Update**: #2377 fails which means `connext-issue.spec.ts` has a flaw, which means this PR now also skips that test.

Apply dummy promise in queue to emulate onIdle

---

.circleci/config.yml
packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json

I'm guessing the name `verify-solc` was confusing enough to not make @kthomas realize that in #2363 the job was failing because he didn't rebuild the artifacts. This new name is much more explicit: `ensure-build-artifacts-match-solidity-code`.

Rename verify-solc job in CircleCI

---

packages/node/src/methods/queued-execution.ts
packages/node/test/unit/queued-execution.spec.ts

Earlier today I made this issue: https://github.com/sindresorhus/p-queue/issues/82
I noticed just now I could use the `Deferred` class to get around this.
This makes the code cleaner.
Also for the #2386 PR I am working on, this means the lock is only requested once per queue not twice (which was annoying).

Remove unnecessary Queue::add in addToManyQueues

---

packages/node/test/integration/connext-issue.spec.ts
packages/node/test/integration/connext-utils.ts
packages/node/test/integration/utils.ts
yarn.lock

Cleans up the `connext-issue.spec.ts` file, also creates a dedicated spot to insert connext specific utils

[node] Clean connext test

---

packages/node/src/rpc-router.ts

When we run our stack with local CF code (i.e. not from NPM), we see an issue sometimes where this function is accessed before the class has been initialized. This should fix those cases.

[node] Fix RPC router issue

---

packages/node/package.json
packages/simple-hub-server/package.json

https://github.com/counterfactual/monorepo/pull/2456 forgot to bump the node version so this PR is doing that.

[node] Bump node version

---

packages/node/src/api.ts
packages/node/src/machine/enums.ts
packages/node/src/machine/protocol-runner.ts
packages/node/src/machine/types.ts
packages/node/src/message-handling/handle-node-message.ts
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/models/state-channel.ts
packages/node/src/protocol/index.ts
packages/node/src/protocol/propose.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/reject-install-virtual-with-postgres.spec.ts
packages/node/test/integration/reject-install-virtual.spec.ts
packages/node/test/integration/utils.ts
packages/types/src/node.ts

The Node handled proposals before, but now it is is something that the `protocolRunner` manages.

Adds a PROPOSE protocol to replace Node's propose mechanic

---

packages/cf-funding-protocol-contracts/test/single-asset-two-party-coin-transfer-from-virtual-app-interpreter.spec.ts
packages/node/src/models/state-channel.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/test/machine/integration/install-virtual.spec.ts

`capitalProvided` could be stored as a `string`

Remove unnecessary serialization type

---

packages/node/src/message-handling/handle-protocol-message.ts
packages/node/test/integration/install.spec.ts

Apps were not being removed from the proposed apps list in the state channel when the protocol completed for the non-initiating party.
Fixed by defaulting to original accessing of `appInstanceId`, but adding another check in case it was in the `params` of the `data` obj.
May want to clean up the casting, or the added place for the test stubs, but functional

[node] proposed app removal

---

packages/cf.js/src/app-factory.ts
packages/cf.js/test/app-factory.spec.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/test/integration/install-concurrent-mixed.spec.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/reject-install-virtual.spec.ts
packages/node/test/integration/utils.ts
packages/types/src/node.ts

remove all `PROPOSE_INSTALL_VIRTUAL`
this is a breaking API change, but leaving it in events specifically is weird.

[types, node, cf.js] clean enums
