package.json
packages/apps/contracts/CommitRevealApp.sol
packages/apps/package.json
packages/contracts/contracts/MinimumViableMultisig.sol
packages/contracts/contracts/NonceRegistry.sol
packages/contracts/contracts/Registry.sol
packages/contracts/contracts/delegateTargets/ConditionalTransfer.sol
packages/contracts/contracts/test/loadContracts.sol
packages/contracts/migrations/2_deploy_contracts.js
packages/contracts/package.json
packages/contracts/test/helpers/cfhelpers.ts
packages/contracts/test/helpers/multisig.ts
packages/contracts/test/integration/commitReveal.spec.ts
packages/contracts/test/unit/conditionalTransfer.spec.ts
packages/contracts/test/unit/stateChannel.spec.ts
packages/test-utils/package.json
packages/test-utils/src/utils.ts
yarn.lock

Test for happy path of a Counterfactual app:
1. Deploy & fund multisig with A and B as signers
2. Deploy GuessNumber app
3. Deploy StateChannel via Registry
4. `setState` on StateChannel with a terminal state
5. `setResolution` on StateChannel
6. `setNonce` and `finalizeNonce` on NonceRegistry
7. `executeStateChannelConditionalTransfer` on ConditionalTransfer from multisig
8. Confirm that A and B's ETH balances are correct
Misc:
* Helper class for dealing with Multisigs
* New function in Utils: `deployContractViaRegistry`
* Fix security issue in MinimumViableMultisig.setup
* Fix delegatecall bug in `executeStateChannelConditionalTransfer`
TODO: 
- ~Fix tests~
- ~Merge in `develop`~

Basic lifecycle test for GuessNumber App

---

packages/contracts/contracts/Conditional.sol
packages/contracts/contracts/StateChannel.sol

This PR adds the `view` modifier to functions in `Conditional.sol` and `StateChannel.sol` which only do staticcalls

Add view modifier

---

contracts/apps/CommitRevealApp.sol
contracts/apps/CountingApp.sol
contracts/apps/Nim.sol
contracts/apps/PaymentApp.sol
contracts/test/loadContracts.sol
package.json
test/integration/nim.spec.ts
yarn.lock

Removes dependency on https://github.com/counterfactual/apps

Moves apps back alongside contracts

---

contracts/MinimumViableMultisig.sol

this variable seems to be unused

delete `isOwner` in MinimumViableMultisig

---

package.json

Useful for ensuring consistency.

Make a hard reference to a commit of the configs repo

---

contracts/NonceRegistry.sol
contracts/delegateTargets/ConditionalTransfer.sol
test/integration/commitReveal.spec.ts
test/unit/nonceRegistry.spec.ts
utils/multisig.ts

This PR allows dependency nonces to be treated in a "packed" format (https://gist.github.com/IIIIllllIIIIllllIIIIllllIIIIllllIIIIll/af044ce89cdd6839453afcffa6c43302).

Support packed nonce

---

contracts/NonceRegistry.sol

add a function to check if a nonce has been set

nonceIsSet

---

ARCHITECTURE.md
README.md
contracts/StateChannel.sol
contracts/apps/CommitRevealApp.sol
contracts/apps/CountingApp.sol
contracts/apps/Nim.sol
contracts/apps/PaymentApp.sol
contracts/apps/TicTacToe.sol
contracts/delegateTargets/ConditionalTransfer.sol
contracts/delegateTargets/VirtualAppAgreement.sol
contracts/lib/StaticCall.sol
contracts/lib/Transfer.sol
contracts/test/ExampleTransfer.sol
test/integration/countingGame.spec.ts
test/integration/twoPartyPayments.spec.ts
test/unit/conditionalTransfer.spec.ts
test/unit/transfer.spec.ts
yarn.lock

- Rename Transfer.Details to Transfer.Transaction
- Rename Transfer.executeTransfer() to Transfer.execute()
- Convert `data` field in Transfer.Transaction to bytes[]
- Rename `amount` field in Transfer.Transaction to `value`

Rename Transfer.Details to Transfer.Transaction

---

packages/contracts/contracts/NonceRegistry.sol

This PR deletes some dead code.

[contracts] delete isFinalized120i and isFinalized128

---

packages/iframe-wallet-poc/iframe-wallet/index.js
packages/iframe-wallet-poc/src/iframe/wallet.ts
packages/machine/src/middleware/cf-operation/types.ts
packages/machine/src/utils/network-context.ts
packages/machine/test/integration/cf-operations.spec.ts

This PR improves documentation of `NetworkContext`

document NetworkContext

---

packages/machine/src/middleware/state-transition/state-transition.ts

replace enacted with committed

---

packages/machine/src/middleware/cf-operation/cf-multisend-op.ts
packages/machine/src/middleware/cf-operation/cf-op-generator.ts
packages/machine/src/middleware/cf-operation/cf-op-install.ts
packages/machine/src/middleware/cf-operation/cf-op-setstate.ts
packages/machine/src/middleware/cf-operation/cf-op-setup.ts
packages/machine/src/middleware/cf-operation/types.ts
packages/machine/src/middleware/state-transition/install-proposer.ts
packages/machine/test/integration/cf-operations.spec.ts
packages/machine/test/unit/state-transition.spec.ts

rename CfStateChannel to CfAppInstance

---

packages/contracts/test/integration/twoPartyPayments.spec.ts
packages/contracts/utils/appInstance.ts
packages/machine/src/middleware/cf-operation/cf-op-setstate.ts
packages/machine/src/middleware/state-transition/install-proposer.ts
packages/machine/src/state.ts
packages/machine/src/types.ts

- rename StateChannel -> AppInstance in comments
- rename AppChannelInfo{s} -> AppInstanceInfo{s}
- delete AppChannelInfoImpl

rename some symbols related to AppInstance.sol

---

packages/contracts/contracts/NonceRegistry.sol
packages/machine/src/middleware/cf-operation/cf-op-install.ts
packages/machine/src/middleware/cf-operation/cf-op-setup.ts

- rename depNonceKey -> uninstallKey to match contracts
- improve NonceRegistry comments

rename depNonceKey -> uninstallKey, improve NonceRegistry comments

---

packages/contracts/contracts/NonceRegistry.sol
packages/contracts/test/unit/nonceRegistry.spec.ts

This PR deletes code that is no longer used

delete unused code

---

packages/contracts/contracts/NonceRegistry.sol

mark computeKey as pure

---

packages/machine/src/vm.ts

Adds some minor improvements to the VM code. See commits for more info.

[machine] Polishes instantiation of VM and removes if-wrapping around sendResponse() 

---

packages/cf.js/src/channel.ts
packages/iframe-wallet-poc/iframe-wallet/index.js
packages/iframe-wallet-poc/test/common.ts
packages/iframe-wallet-poc/test/wallet-test.spec.ts
packages/machine/src/middleware/cf-operation/cf-op-generator.ts
packages/machine/src/middleware/middleware.ts
packages/machine/src/middleware/state-transition/install-proposer.ts
packages/machine/src/middleware/state-transition/uninstall-proposer.ts
packages/machine/src/middleware/state-transition/update-proposer.ts
packages/machine/src/state.ts
packages/machine/test/integration/cf-operations.spec.ts
packages/machine/test/integration/lifecycle.spec.ts
packages/machine/test/integration/test-setup.ts
packages/machine/test/unit/state-transition.spec.ts

- add a `OpCodeResult` type annotation
- rename `appChannels` -> `appInstances`
- rename `newAppChannel` -> `newAppInstance`

rename appChannels -> appInstances

---

packages/contracts/contracts/Registry.sol
packages/contracts/contracts/lib/Signatures.sol

This checks whether the contract being made a call to via the registry actually exists or not.
It also adds better error messaging when a signature being used is invalid.

[contracts] Contract existence check

---

packages/cf.js/src/channel.ts
packages/iframe-wallet-poc/iframe-wallet/index.js
packages/iframe-wallet-poc/src/iframe/user.ts
packages/iframe-wallet-poc/src/iframe/wallet.ts
packages/machine/src/instruction-executor.ts
packages/machine/src/node-state.ts
packages/machine/test/unit/state-transition.spec.ts

The two interfaces `ChannelStates` and `StateChannelInfos` are the same.

merge ChannelStates and StateChannelInfos interfaces

---

packages/machine/src/action.ts
packages/machine/src/types.ts
packages/machine/src/write-ahead-log.ts

These two interfaces are the same

merge MiddlewareResult and OpCodeResult

---

.circleci/config.yml
README.md
packages/contracts/README.md
packages/contracts/package.json

This updates the documentation to refer to the correct yarn script to locally migrate the contracts for testing.

[contracts] Update migrate documentation step

---

packages/iframe-wallet-poc/iframe-wallet/index.html
packages/iframe-wallet-poc/iframe-wallet/index.js
packages/machine/rollup.config.js

Final tweaks to the legacy build to get ethmo working again.

ethmo support

---

packages/playground/package.json
packages/playground/src/components/app-home/app-home.tsx
packages/playground/tslint.json

Add linting to playground and scripts

[playground] Add linting to playground and scripts

---

README.md
netlify.toml
packages/cf.js/README.md
packages/contracts/README.md

[contracts] Fix various spelling mistakes

---

packages/contracts/package.json

[contracts] no lint staged

---

packages/cf.js/package.json
packages/cf.js/rollup.config.js
packages/cf.js/src/legacy/app-instance.ts
packages/cf.js/src/legacy/app/index.ts
packages/cf.js/src/legacy/channel.ts
packages/cf.js/src/legacy/eth-balance-refund-app.ts
packages/cf.js/src/legacy/network.ts
packages/cf.js/src/legacy/node/index.ts
packages/cf.js/src/legacy/types.ts
packages/cf.js/src/legacy/utils/free-balance.ts
packages/cf.js/src/legacy/utils/index.ts
packages/cf.js/src/legacy/utils/nonce.ts
packages/cf.js/src/legacy/utils/peer-balance.ts
packages/cf.js/src/legacy/utils/serializer.ts
packages/cf.js/src/provider.ts
packages/cf.js/src/utils/abi.ts
packages/cf.js/src/utils/signature.ts
packages/cf.js/test/utils/signature.spec.ts
packages/node-provider/package.json
packages/node-provider/rollup.config.js
packages/node-provider/src/index.ts
packages/playground-poc/README.md
packages/playground-poc/package.json
packages/playground-poc/public/index.html
packages/playground-poc/server/index.js
tsconfig.json
yarn.lock

@mvanderh 
- used `cuid` over `uuid`
- kept dependencies external
- removed lodash entirely

[poc] bridges cf.js into playground-poc for testing

---

packages/cf.js/API_REFERENCE.md

- Explain message format
- Add requestId field

[CFjs] Add message format section to Node Spec

---

package.json
packages/playground/src/components/dapp-container/dapp-container.e2e.ts

Addresses OOM issue by reducing parallelism (short term fix).

[monorepo] Fix test execution failure

---

package.json
yarn.lock

Pin yarn engine used, as documented, to prevent divergence across `yarn.lock` submissions.

[monorepo] Pin yarn engine

---

packages/playground/src/components/app-root/app-root.scss
packages/playground/src/global/_layout.scss

[playground] ensure iframe fills remaining height

---

packages/cf.js/package.json
packages/common-types/package.json
packages/contracts/package.json
packages/machine/package.json
packages/node/package.json
yarn.lock

according to @snario, this prevents `bignumber("0x0") !== bignumber("0x00")` errors

[monorepo] update ethers

---

packages/contracts/contracts/MinimumViableMultisig.sol

edit MinimumViableMultisig docstring for clarity

[contracts] [docs] edit MinimumViableMultisig docstring

---

packages/cf.js/API_REFERENCE.md

various fixes to the docs related to `AppInstanceInfo.id` and the `appInstanceId` parameters

[cf.js] docs fixes around ID

---

packages/contracts/utils/misc.ts

- restrict input type
- no custom message

[contracts] clean up assertRejects

---

packages/node/src/channels.ts
packages/node/src/index.ts
packages/node/src/methods/app-instance-operations.ts
packages/node/src/methods/install-operations.ts
packages/node/src/methods/multisig-operations.ts
packages/node/src/methods/request-handler.ts
packages/node/src/node.ts
packages/node/src/service-interfaces.ts
packages/node/src/services.ts
packages/node/test/integration/cross-node-multisig-creation.spec.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/node-communication.spec.ts
packages/node/test/integration/node-store.spec.ts
packages/node/test/integration/propose-install.spec.ts
packages/node/test/integration/services/firebase-service.ts
packages/node/test/mock-services/mock-messaging-service.ts
packages/node/test/mock-services/mock-store-service.ts

This exposes default implementations of the service interfaces the Node expects to have dependency injected into it.
The implementation uses a Firebase backend and provides a service factory specifically for Firebase-coupled services. Node consumers can use said factory by providing a Firebase configuration
https://github.com/counterfactual/monorepo/blob/a92f415d8def0d1782f97496af30799d2a03d8e7/packages/node/src/services.ts#L16-L23

[node] Default service implementations

---

packages/contracts/package.json

Reverts counterfactual/monorepo#363

Revert "Update solium in group default to the latest version 🚀"

---

packages/cf.js/README.md
packages/contracts/README.md
packages/dapp-high-roller/README.md
packages/machine/README.md
packages/playground/README.md
packages/typescript-typings/README.md

Made the titles a bit more consistent for library and project packages and some tiny copy touchups

Slight cleanup to README titles and descriptions

---

packages/playground/src/components/node-listener/node-listener.tsx
packages/playground/src/index.html

[playground] Fixes "commonTypes" pre-render error

---

packages/cf.js/API_REFERENCE.md

This error was pointed out in https://github.com/counterfactual/monorepo/pull/340#discussion_r241824328

[cf.js] fix inaccuracy in cf.js API reference

---

packages/contracts/contracts/NonceRegistry.sol
packages/contracts/contracts/StateChannelTransaction.sol
packages/contracts/test/nonce-registry.spec.ts

More clear to what it actually represents.

Rename isFinalized to isFinalizedOrHasNeverBeenSetBefore

---

packages/cf.js/API_REFERENCE.md

Add proposeVirtualInstall and installVirtual methods to Node API. This enables installation of virtual apps via metachannels.

[CFjs] Add proposeVirtualInstall and installVirtual methods to Node API spec

---

packages/node/src/channels.ts
packages/node/src/node.ts
packages/node/test/integration/cross-node-multisig-creation.spec.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/node-store.spec.ts
packages/node/test/integration/propose-install.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/node.spec.ts

Will be useful very soon. Also this is inside @cf19drofxots's PR: #398

[node] Add NetworkContext to Node constructor

---

packages/machine/src/models/state-channel.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/unit/models/state-channel/install.spec.ts
packages/machine/test/unit/models/state-channel/set-state.spec.ts
packages/machine/test/unit/models/state-channel/uninstall-app.spec.ts

This adds a check for the right sequence number being specified for an AppInstance being installed into a StateChannel.

[machine] Add seq number check

---

packages/machine/src/instruction-executor.ts
packages/machine/src/protocol-types-tbd.ts
packages/machine/src/protocol/update.ts

[machine] rename UpdateData -> UpdateParams

---

packages/machine/src/instruction-executor.ts
packages/machine/src/protocol-types-tbd.ts
packages/machine/src/protocol/update.ts

Reverts counterfactual/monorepo#418

Revert "[machine] rename UpdateData -> UpdateParams"

---

packages/cf.js/.gitignore
packages/cf.js/package.json
packages/cf.js/src/app-factory.ts
packages/cf.js/src/app-instance.ts
packages/cf.js/src/provider.ts
yarn.lock

- Add docs for all methods and classes in CFjs. (not done: events, typedefs, utils)
- Added a `docs` script to package.json using Typedoc that generates documentation from this

[CFjs] Added documentation and docgen script

---

packages/machine/src/ethereum/types.ts

[machine] delete ExecTransactionCalldata

---

greenkeeper.json
packages/cf.js/rollup.config.js
packages/machine/rollup.config.js
packages/node/rollup.config.js
packages/types/rollup.config.js

[monorepo] Format rollup.config.js & update greenkeeper

---

packages/node/src/methods/app-instance-operations.ts
packages/node/src/methods/errors.ts
packages/node/src/methods/install-operations.ts
packages/node/src/methods/request-handler.ts
packages/node/src/store.ts
packages/node/test/integration/get-state.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/services/memory-store-service.ts
packages/node/test/unit/getState.spec.ts
packages/node/test/unit/install.spec.ts
packages/node/test/unit/utils.ts

This implements the [`getState`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-getstate) public API method.

[node] Implements AppInstance getState

---

packages/dapp-tic-tac-toe/package.json

This task is needed to configure the build command for the Netlify site where we'll deploy TTT.

[dapp-tic-tac-toe] Adds "yarn netlify" task

---

build.sh

[monorepo] Add newlines to build.sh

---

packages/machine/src/instruction-executor.ts
packages/machine/test/unit/ethereum/install-commitment.spec.ts
packages/machine/test/unit/instruction-executor.spec.ts
packages/machine/test/unit/models/state-channel/install.spec.ts
packages/machine/test/unit/models/state-channel/set-state.spec.ts
packages/machine/test/unit/models/state-channel/setup-channel.spec.ts
packages/machine/test/unit/models/state-channel/uninstall-app.spec.ts

 [monorepo] miscellaneous cleanup

---

packages/playground-server/src/controllers/matchmake.ts
packages/playground-server/src/types.ts
packages/playground-server/test/api.spec.ts

Before:
```json
{
"ok": true,
"data": {
"username": "delilah", 
"peerAddress": "0xdab500c650725c2f1af0b09df327d2d3ef3cefca"
}
}
```
After:
```json
{
"ok": true,
"data": {
"user": {
"username": "joe",
"address": "0x0f693cc956df59dec24bb1c605ac94cadce6014d"
},
"opponent": {
"username": "delilah", 
"address": "0xdab500c650725c2f1af0b09df327d2d3ef3cefca"
},
"intermediary": "0x3b1c5dFE09187aC3F015139AD79ff7E9a77828Cf"
}
}
```

[playground-server] Adds user data + intermediary to /api/matchmake

---

packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MAppRegistryCore.sol
packages/contracts/contracts/mixins/MixinSetResolution.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/test/app-registry-new.spec.ts
packages/contracts/test/app-registry.spec.ts
packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/contracts/test/utils/index.ts
packages/dapp-high-roller/src/data/types.ts
packages/machine/src/ethereum/utils/free-balance.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/integration/setup-then-set-state.spec.ts
packages/machine/test/unit/ethereum/install-commitment.spec.ts
packages/machine/test/unit/ethereum/set-state-commitment.spec.ts
packages/machine/test/unit/models/app-instance/app-instance.spec.ts
packages/machine/test/unit/models/state-channel/install.spec.ts
packages/machine/test/unit/models/state-channel/set-state.spec.ts
packages/machine/test/unit/models/state-channel/setup-channel.spec.ts
packages/machine/test/unit/models/state-channel/uninstall-app.spec.ts
packages/node/src/methods/install-operations.ts
packages/node/test/unit/utils.ts
packages/types/src/app-instance.ts
packages/types/src/index.ts

Remove sighashes from AppInterface in TS and AppInterface in Solidity

---

packages/machine/src/protocol/install-virtual-app.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/setup.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/src/protocol/utils/signature-forwarder.ts

[machine] Rename state to stateChannel for clarity

---

packages/node/src/api-spec.ts
packages/node/src/methods/app-instance-operations.ts
packages/node/src/methods/index.ts
packages/node/src/methods/install-operations.ts
packages/node/src/methods/multisig-operations.ts
packages/node/src/node.ts
packages/node/src/request-handler.ts

Some file restructuring to make explicit the public API.

[node] Create api-spec.ts

---

packages/dapp-high-roller/src/components/app-provider/app-provider.tsx

Fix call to updateAppInstance with data.data.appInstance

[dapp-high-roller] Fix call to updateAppInstance with data.data.appInstance

---

packages/dapp-tic-tac-toe/lib/dapp-tic-tac-toe.js
packages/dapp-tic-tac-toe/package.json
packages/dapp-tic-tac-toe/src/MockNodeProvider.js

Fix for winning that was showing LOST state in dapp Tic Tac Toe
Also remove unneeded file in lib folder. There is a test file here that might also be redundant right now:
https://github.com/counterfactual/monorepo/blob/master/packages/dapp-tic-tac-toe/__tests__/dapp-tic-tac-toe.test.js

[dapp-tic-tac-toe] Fix for winning that was showing LOST state

---

packages/node/src/events/install/controller.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/node.ts
packages/node/test/unit/install.spec.ts
yarn.lock

~Currently hits an error until we merge in #498.~
EDIT: Rebased after it was merged

[node] Add runInstallProtocol in install method

---

packages/cf.js/API_REFERENCE.md
packages/cf.js/test/app-instance.spec.ts
packages/cf.js/test/provider.spec.ts
packages/node/src/events/propose-install-virtual/controller.ts
packages/node/src/events/propose-install-virtual/operation.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/operation.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/app-instance/propose-install/operation.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/utils.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/get-state.spec.ts
packages/node/test/integration/propose-install-virtual.spec.ts
packages/node/test/integration/propose-install.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/utils.ts
packages/types/src/data-types.ts
packages/types/src/node-protocol.ts

This fully implements the [`proposeInstallVirtual`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-proposeinstallvirtual) API method.
https://github.com/counterfactual/monorepo/blob/propose_install_virtual_p2/packages/node/test/integration/propose-install-virtual.spec.ts#L70-L134

[node] Implement proposeInstallVirtual

---

packages/node/tsconfig.json

For https://github.com/counterfactual/monorepo/pull/469#issuecomment-454057883

Add include for tests folder in tsconfig

---

packages/node/src/api-router.ts
packages/node/src/events/index.ts
packages/node/src/events/install-virtual/controller.ts
packages/node/src/methods/app-instance/install-virtual/controller.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/index.ts
packages/node/src/types.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/utils.ts

This implements the [`installVirtual`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-installvirtual) public API method.

[node] Implements installVirtual 

---

packages/node/src/node.ts

Not a priority but thought I'd put this here

[node] Rename init

---

packages/cf.js/package.json
packages/cf.js/src/provider.ts
packages/dapp-high-roller/src/index.html
packages/dapp-high-roller/test-setup.js
packages/playground/src/index.html
yarn.lock

Brings the usage of ID generation to a consistent pattern across the packages.

[cf.js] Replace cuid with uuid

---

packages/cf.js/package.json

As the currently published package details are stale.

[cf.js] Bump package patch version

---

packages/cf.js/package.json

[cf.js] fix: repository link for cf.js

---

packages/machine/src/ethereum/eth-virtual-app-agreement-commitment.ts
packages/machine/src/ethereum/install-commitment.ts
packages/machine/src/ethereum/multisend-commitment.ts
packages/machine/src/ethereum/uninstall-commitment.ts
packages/machine/src/protocol/install.ts

This PR removes `dependencyNonceSalt` and `dependencyNonceValue` from `MultisigCommitment`

[machine] inline computation of dependency nonce related values

---

packages/node/package.json
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts
yarn.lock

This just adds a test to ensure `takeAction` works as expected on virtual AppInstances.
https://github.com/counterfactual/monorepo/blob/take_action_virtual/packages/node/test/integration/take-action-virtual.spec.ts#L187-L217

[node] Adds test for taking action on virtual AppInstances

---

packages/machine/src/middleware.ts
packages/machine/src/opcodes.ts
packages/machine/src/protocol/install-virtual-app.ts
packages/machine/src/protocol/install.ts
packages/machine/src/protocol/setup.ts
packages/machine/src/protocol/uninstall.ts
packages/machine/src/protocol/update.ts
packages/machine/src/protocol/utils/inbox-validator.ts
packages/machine/src/protocol/utils/signature-forwarder.ts
packages/machine/test/unit/instruction-executor.spec.ts
packages/node/src/events/protocol-message/controller.ts
packages/node/src/node.ts

Slightly more easy to reason about.

[machine, node] Change IO_WAIT to IO_SEND_AND_WAIT

---

packages/apps/contracts/CommitRevealApp.sol
packages/apps/contracts/CountingApp.sol
packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/PaymentApp.sol
packages/apps/contracts/TicTacToeApp.sol
packages/apps/test/high-roller-app.spec.ts
packages/apps/test/nim.spec.ts
packages/apps/test/payment.spec.ts
packages/apps/test/tictactoe.spec.ts
packages/node/src/methods/app-instance/take-action/operation.ts
yarn.lock

I think we will probably need to also update how `applyAction` is used in the Node @cf19drofxots

[apps] Upgrade apps to use CounterfactualApp

---

packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/widgets/widget-connection/widget-connection.tsx
yarn.lock

no more connecting to undefined

---

packages/apps/test/high-roller-app.spec.ts
packages/apps/test/nim.spec.ts
packages/apps/test/payment.spec.ts
packages/apps/test/tictactoe.spec.ts
packages/cf.js/src/app-factory.ts
packages/cf.js/src/app-instance.ts
packages/cf.js/src/types/events.ts
packages/dapp-high-roller/src/data/mock-app-instance.ts
packages/dapp-high-roller/src/data/types.ts
packages/machine/src/ethereum/virtual-app-set-state-commitment.ts
packages/machine/src/models/app-instance.ts
packages/machine/src/models/state-channel.ts
packages/machine/src/protocol-types-tbd.ts
packages/node/src/methods/app-instance/get-state/operation.ts
packages/node/src/methods/app-instance/take-action/operation.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/store.ts
packages/node/test/integration/cant-take-action.spec.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/utils.ts
packages/types/src/index.ts
packages/types/src/node-protocol.ts
packages/types/src/node.ts
packages/types/src/simple-types.ts

Much clearer what it represents.

Rename AppState type to SolidityABIEncoderV2Struct

---

packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/machine/src/ethereum/eth-virtual-app-agreement-commitment.ts
packages/machine/src/models/state-channel.ts
packages/machine/test/integration/bignumber-jest-matcher.ts
packages/machine/test/integration/eth-virtual-app-agreement-commitment.spec.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/test/integration/set-state.spec.ts
packages/machine/test/integration/setup-then-set-state.spec.ts

- adds integration tests for  `eth-virtual-app-agreement-commitment`

[machine] add integration test

---

packages/node/src/api-router.ts
packages/node/src/methods/app-instance/get-app-instance/controller.ts
packages/node/src/methods/errors.ts
packages/node/src/methods/index.ts
packages/node/src/store.ts
packages/node/test/integration/get-app-instance.spec.ts

This implements [`getAppInstanceDetails`](https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/API_REFERENCE.md#method-getAppInstanceDetails) to get details of an AppInstance.

[node] Implements getAppInstanceDetails 

---

packages/apps/contracts/HighRollerApp.sol

[dapp-high-roller] Fix spelling mistake

---

packages/apps/networks/3.json

This redeploys the contracts to Ropsten as the previous set of addresses were stale.

[apps] Update contract addresses

---

packages/node/src/api-router.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/types.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts

Note that I made the minimal change to get this working and merged - I'll put up a following PR to clean up the internals to remove any remaining discrepancies.

[node] Remove takeActionEvent in favor of the existing updateStateEvent

---

packages/machine/src/models/state-channel.ts

`uninstallApp` should increment the free balance, not decrement it

[machine] fix sign error in uninstallApp

---

packages/cf.js/API_REFERENCE.md
packages/cf.js/src/provider.ts
packages/node/src/events/take-action/controller.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/types.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts

This syncs the data being passed from the Node to what cf.js expects.

[node] Fix data being sent out for state update

---

packages/dapp-high-roller/src/components/app-game-coins/app-game-coins.tsx
packages/dapp-high-roller/src/components/app-logo/app-logo.tsx
packages/playground/src/components/widgets/widget-connection/widget-connection.tsx

* adds a tooltip when hover over the "No Connection" icon in the playground
* adds falling coin animation to the landing page of high roller

[playground][high-roller] Ptb/playground polish

---

packages/machine/src/ethereum/virtual-app-set-state-commitment.ts

- make first argument to `solidityPack` correctly sized
- fix comment; should be kept in sync with `digest`

[machine] fix bugs in digest calculation for virtual app set state

---

packages/node/src/utils.ts

Adds a simple error handling case to catch and throw said error with a better description / context.

[node] Better error message for channel non-existence

---

packages/contracts/package.json
yarn.lock

Old version doesn't exist anymore

Change openzeppelin-solidity to fixed version

---

packages/playground/src/components/layout/layout-header/header-account/header-account.scss
packages/playground/src/components/widgets/widget-logo/widget-logo.scss

[playground] Fixes header size by adjusting button/logo sizes

---

packages/dapp-tic-tac-toe/src/Game.jsx
packages/dapp-tic-tac-toe/src/components/Board.jsx
packages/dapp-tic-tac-toe/src/components/Player.jsx
packages/dapp-tic-tac-toe/src/index.css
packages/dapp-tic-tac-toe/src/utils/check-end-conditions.js
yarn.lock

* display winner status at the top of the screen
* shower the winner with coins!!
* correctly detect vertical wins

[ttt] correctly display ttt victory

---

packages/apps/test/tictactoe.spec.ts

Fix Tic Tac Toe test description from `can notplay` to `cannot play`
Also fixes var name from `tictactoe` to `ticTacToe`

[dapp-tic-tac-toe] Fix Tic Tac Toe test description

---

packages/machine/src/protocol/install-virtual-app.ts

- sort `proposeStateTransition{1, 2, 3}`
- introduce `createTarget` helper

[machine] clean up install-virtual-app

---

packages/dapp-high-roller/src/components/app-game/app-game.tsx

Replace `nullValueBytes32` const with `ethers.constants.HashZero`

[dapp-high-roller] Replace nullValueBytes32 with HashZero

---

packages/playground-server/test/api.spec.ts
packages/playground-server/test/mock-data.ts

After #653 got merged, some of the Playground Server's tests remained to be fixed or re-enabled. This PR makes sure all tests are passing correctly.

[playground-server] Re-enables and fixes all tests

---

packages/playground-server/src/resources/app/processor.ts

There was a bug in a log message that was preventing the apps list from being shown. This PR fixes that.

[playground-server] Fixes log bug for app registry

---

packages/machine/src/models/state-channel.ts
packages/machine/src/protocol/install-virtual-app.ts
packages/machine/src/types.ts
packages/machine/src/virtual-app-key.ts

create a channel for target virtual app to live in

[machine] create a channel for target virtual app

---

packages/dapp-high-roller/src/components/app-game/app-game.tsx

Remove unused function in app-game.tsx

[dapp-high-roller] Remove unused function

---

.circleci/config.yml

[playground-server][dapp-tic-tac-toe] Add packages' tests to CI

---

packages/machine/src/protocol/install-virtual-app.ts

Just pulling stuff out of `liam/virtualapp` to keep that PR to its essence

[machine] Format some code a bit

---

packages/node/src/index.ts
packages/playground-server/src/node.ts
packages/playground-server/test/api.spec.ts

This prevents the store index key being randomly generated when it shouldn't be.

[playground-server] Fix pg store service key

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/typescript-typings/types/ethers/index.d.ts

This estimates how much gas to use for the deposit transaction.

[playground] Use non-zero gas fee for transaction

---

packages/dapp-high-roller/src/components/app-wager/app-wager.scss
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/dapp-tic-tac-toe/src/index.css
packages/playground/src/components/node-listener/dialogs/insufficient-funds/dialog-insufficient-funds.tsx
packages/playground/src/components/node-listener/dialogs/propose-install/dialog-propose-install.tsx
packages/playground/src/components/node-listener/node-listener.tsx

[dapp-high-roller] [dapp-tic-tac-toe] [playground] Check for minimum balance before proposing an install and before accepting an install

---

packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/data/mock-app-instance.ts
packages/dapp-high-roller/src/data/types.ts
packages/dapp-tic-tac-toe/src/App.js
packages/dapp-tic-tac-toe/src/Game.jsx

- **High Roller**: if the game stage is `DONE`, we call `appInstance.uninstall()`.
- **Tic-Tac-Toe**: if the game declares a winner, we call `appInstance.uninstall()`.
This PR includes the `intermediaryIdentifier` parameter in the call.

[dapp-high-roller] [dapp-tic-tac-toe] Implements uninstall call in High Roller & TTT

---

packages/playground-server/src/db.ts
packages/playground-server/src/errors.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground/src/components/account/account-register/account-register.tsx

__Errors are back!__
This PR moves all minimal validation code _before_ creating the multisig.

[playground-server] [playground] Restores API validation for account registration

---

packages/cf.js/API_REFERENCE.md
packages/machine/src/models/state-channel.ts
packages/machine/src/xkeys.ts
packages/node/jest.config.js
packages/node/src/api-router.ts
packages/node/src/events/deposit/controller.ts
packages/node/src/events/index.ts
packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/methods/errors.ts
packages/node/src/methods/index.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/services.ts
packages/node/src/types.ts
packages/node/src/utils.ts
packages/node/test/contract-deployments.jest.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/node/test/integration/services/firebase-service.ts
packages/node/test/integration/utils.ts
packages/node/test/node-test-environment.jest.js
packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/types/src/node-protocol.ts

This adds secure depositing to a channel, instead of the current naive implementation of simply sending some funds into a channel.
Note this also adds a method to the Node to retrieve a channel's free balance. Useful in checking the owners' balances.

[node] Secure deposit

---

packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx

**Bonus feature:** Login signature is now handled by Ethers!

[playground] Implements "Login here" action from Account Registration

---

packages/dapp-high-roller/package.json
packages/machine/src/ethereum/eth-virtual-app-agreement-commitment.ts
packages/machine/src/models/eth-virtual-app-agreement-instance.ts
packages/machine/src/protocol/install-virtual-app.ts

- add checks that beneficiary address is an actual address in constructor of ETHVirtualAppAgreementCommitment
- add `beneficiary{1,2}` to `ETHVirtualAppAgreementInstance` and pass this into the commitment

[machine] install-virtual-app pass key and beneficiaries

---

packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
yarn.lock

[playground] Shows "Login Failed" message if /api/session-requests throws an error

---

packages/playground/src/components/app-root/app-root.scss
packages/playground/src/components/layout/layout-header/layout-header/layout-header.scss
packages/playground/src/components/widgets/widget-dialog/widget-dialog.scss
packages/playground/src/components/widgets/widget-logo/widget-logo.scss

- Background color is now greyish
- Header is white (to override grey)
- Header border bottom is grey instead of blue
- Logo is rounded

[playground] Styles some components on Playground

---

packages/node/src/node.ts

Fix spelling mistake `asyncronously` -> `asynchronously`

[node] Fix spelling mistake `asyncronously` -> `asynchronously`

---

packages/playground/src/components/account/account-exchange/account-exchange.scss
packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/app-home/app-home/app-home.scss
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/form/form-button/form-button.scss
packages/playground/src/components/form/form-input/form-input.scss
packages/playground/src/components/layout/layout-header/header-account/header-account.scss
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/components/layout/layout-header/layout-header/layout-header.scss
packages/playground/src/components/node-listener/node-listener.tsx
packages/playground/src/components/webthree-connector/webthree-connector.tsx
packages/playground/src/components/widgets/widget-connection/widget-connection.scss
packages/playground/src/components/widgets/widget-connection/widget-connection.tsx
packages/playground/src/components/widgets/widget-tooltip/widget-tooltip.scss
packages/playground/src/data/network.tsx
packages/playground/src/global/_button.scss
packages/playground/src/global/_variables.scss
yarn.lock

[playground] Implement metamask account checking UI

---

packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/methods/state-channel/withdraw/controller.ts

Note, some of this is already included inside #765

[node] Add gasPrice and gasLimit to tx on deposit and withdraw

---

packages/machine/src/enums.ts
packages/machine/src/middleware.ts
packages/node/src/node.ts

- remove `OP_SIGN_VALIDATE` (the TODO is done)
- remove special-case `keyIndex` calculation (noop)
- add todo to remove `message.protocol` in `makeSigner`

[machine,node] remove unused code

---

packages/contracts/contracts/mixins/MAppCaller.sol

[contracts] Swap view to pure in MAppCaller

---

packages/node/src/node.ts

Solves a potential out of sync problem if message sending is delayed or out of order.

[machine] Grasp promise before awaiting message send

---

packages/machine/src/index.ts
packages/node/src/events/propose-install-virtual/operation.ts
packages/node/src/methods/app-instance/propose-install-virtual/operation.ts
packages/node/src/methods/errors.ts
packages/node/src/utils.ts
packages/node/test/integration/install-virtual.spec.ts

This fixes the issue with being able to install multiple virtual AppInstances, with each having unique IDs.
It also adds a test for this case.

[node] Fix installing multiple virtual app instances

---

packages/playground-server/src/index.ts
packages/playground-server/src/node.ts
packages/playground-server/test/api.spec.ts

This will prevent the server from losing access to funds every time the storage is reset.

[playground-server] Adds NODE_MNEMONIC env-var

---

packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/components/node-listener/node-listener.tsx
packages/playground/src/components/webthree-connector/webthree-connector.tsx
packages/playground/src/components/widgets/widget-connection/widget-connection.tsx
packages/playground/src/data/wallet.tsx

More representative of what it means.

[playground] Rename NetworkTunnel to WalletTunnel

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-tic-tac-toe/src/Wager.jsx

This PR removes the hard-coded zero ETH bets on both dApps.

[dapp-high-roller] [dapp-tic-tac-toe] Enables non-zero ETH bets

---

packages/cf.js/jest.config.js
packages/cf.js/package.json
packages/node-provider/jest.config.js
packages/node-provider/package.json

[monorepo] Separate jest files

---

packages/node/test/global-setup.jest.ts
packages/node/test/global-teardown.jest.ts
packages/playground-server/test/global-setup.jest.ts
packages/playground-server/test/global-teardown.jest.ts

Another tiny thing I noticed today when writing tests

Uses ES6 syntax for global jest functions

---

packages/node/package.json

Add missing peer dependency

---

packages/contracts/contracts/AppRegistry.sol

@patience-tema-baron noticed this earlier

Ignore empty block line warning

---

packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/methods/state-channel/withdraw/operation.ts

Remove file accessor import from @machine

---

packages/machine/src/models/eth-virtual-app-agreement-instance.ts
packages/machine/src/protocol/install-virtual-app.ts

This resolves an overflow issue when installing virtual AppInstances.

[machine] Fix bigNumber issue

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx

[playground] Limits deposits to 1 ETH on Onboarding / Exchange

---

packages/dapp-tic-tac-toe/src/Game.jsx

I haven't tested this since it needs to be deployed to staging to test

[ttt] Check if game over correctly

---

packages/playground/src/components/app-home/app-home/app-home.scss
packages/playground/src/components/app-home/app-home/app-home.tsx

[playground] First stab at a splash screen

---

README.md
packages/apps/package.json
packages/cf.js/package.json
packages/contracts/package.json
packages/dapp-tic-tac-toe/package.json
packages/machine/package.json
packages/node-provider/package.json
packages/node/package.json
packages/playground-server/package.json
packages/playground/package.json
packages/types/package.json
packages/typescript-typings/package.json
yarn.lock

- Published `0.0.4` of `node` and `0.0.5` of `types`
- Updated package.jsons
- Made a README thing

Update npm information

---

packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/app-root/app-root.tsx
yarn.lock

Fix minor issues

---

packages/playground-server/src/db.ts
packages/playground-server/src/resources/user/processor.ts
packages/playground/src/components/account/account-edit/account-edit.tsx
packages/playground/src/components/account/account-register/account-register.scss
packages/playground/src/components/account/account-register/account-register.tsx
packages/playground/src/data/playground-api-client.ts
packages/playground/src/global/_typography.scss
packages/playground/src/types.ts

This PR allows the user to access their account settings and modify their e-mail address. It also updates the UI to make it consistent with the Account Registration screen.

[playground] Implements Account Editing UI

---

packages/node/package.json
packages/node/src/methods/state-channel/deposit/controller.ts
yarn.lock

Fixes the check to use type methods.

[node] Fixes deposit check

---

packages/node/src/methods/state-channel/deposit/operation.ts
packages/playground/src/components/node-listener/node-listener.tsx

This will enable full support in the Kovan testnet.

[playground] [node] Remove calls to provider.estimateGas()

---

packages/machine/src/protocol/uninstall-virtual-app.ts

This PR adds some comments to make checking the machine code against the specs (https://github.com/counterfactual/specs/pull/49/) easier

[machine] add some signature annotations

---

packages/node/src/request-handler.ts

This helped me when testing b/c otherwise I need to inspect the event.

[node] Do a simple check on the event controller

---

packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/node/test/integration/secure-withdraw.spec.ts

These tests weren't actually running.

[node] Add done() param to tests

---

packages/machine/src/protocol/install-virtual-app.ts
packages/node/src/models/proposed-app-instance-info.ts

The limit was set to Zero. It needs to be the sum of the deposits.

[machine,node] Correctly add limit field for virtual apps

---

packages/playground/src/components/dapp-container/dapp-container.tsx

Unless `playground:matchmakeWith` is set, the Playground will match a user with the Dapp's bot.

[playground] Matches dApps with their bots

---

.circleci/config.yml
packages/playground-server/package.json

1. A registry was in the pg-server package json
2. Needed to add ~/.npmrc

Fix npm issues

---

README.md

They weren't there. Omitted the playground ones b.c they aren't "core"

Add README listings for some other CF packages

---

packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/data/account.tsx

[playground] Adds "Log out" feature

---

packages/playground-server/.env-cmdrc
packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx

- Add env var that is defaulted in the code
- Fix UI error preventing showing of balances
- Show alert for weird edge case

Miscellaneous cleanups

---

packages/apps/contracts/TicTacToeApp.sol
packages/apps/test/tictactoe.spec.ts
yarn.lock

This fixes TicTacToe resolve logic for winner/loser which was backwards.
The loser was receiving funds 🙃

[dapp-tic-tac-toe] Fixes TicTacToe resolve logic for winner/loser is backwards

---

packages/apps/networks/3.json
packages/apps/truffle-config.js
packages/dapp-tic-tac-toe/src/Wager.jsx
packages/playground-server/registry.json
packages/playground-server/registry.local.json

Updates the TTT contract address to a newly deployed contract.
https://github.com/counterfactual/monorepo/pull/965

[apps] Update TTT deployed contract address

---

packages/playground/src/components/account/account-edit/account-edit.tsx
packages/playground/src/components/form/form-button/form-button.scss
packages/playground/src/components/form/form-button/form-button.tsx
packages/playground/src/components/layout/layout-header/header-account/header-account.tsx

[playground] Moves "Log out" action to "Account Edit" screen

---

packages/tic-tac-toe-bot/package.json

Removing registry so the package can be published.

[ticTacToeBot] Remove package registry

---

packages/dapp-tic-tac-toe/package.json
yarn.lock

2.1.6 fails. Same bug as https://github.com/facebook/create-react-app/issues/6533

Revert to react script 2.1.5

---

packages/node/src/network-configuration.ts
packages/node/src/node.ts
packages/node/test/integration/cant-take-action.spec.ts
packages/node/test/integration/cross-node-multisig-creation.spec.ts
packages/node/test/integration/get-app-instance.spec.ts
packages/node/test/integration/get-app-instances.spec.ts
packages/node/test/integration/get-state.spec.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/node-store.spec.ts
packages/node/test/integration/propose-install-virtual.spec.ts
packages/node/test/integration/propose-install.spec.ts
packages/node/test/integration/reject-install-virtual.spec.ts
packages/node/test/integration/reject-install.spec.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/node/test/integration/secure-withdraw.spec.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts
packages/node/test/integration/uninstall-virtual.spec.ts
packages/node/test/integration/uninstall.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/node.spec.ts
packages/playground-server/src/node.ts
packages/playground-server/test/api.spec.ts
packages/tic-tac-toe-bot/test/integration.spec.ts

This constant and the corresponding arguments seem unused

[monorepo] remove TEST_NETWORK

---

packages/playground/src/components/app-root/app-root.tsx

Reverts counterfactual/monorepo#971 as that doesn't seem to be the right fix

Revert "[playground] Fix using multisig address for deposit"

---

packages/playground/src/components/layout/layout-header/header-account/header-account.tsx
packages/playground/src/components/layout/layout-header/header-balance/header-balance.e2e.ts
packages/playground/src/components/layout/layout-header/header-balance/header-balance.spec.ts
packages/playground/src/components/layout/layout-header/header-balance/header-balance.tsx
packages/playground/src/components/layout/layout-header/layout-header/layout-header.scss
packages/playground/src/components/layout/layout-header/layout-header/layout-header.tsx

[playground] add logo and balance to mobile header

---

packages/dapp-high-roller/src/components/app-logo/app-logo.tsx
packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/src/components/app-waiting/app-waiting.tsx
packages/playground-server/src/node.ts
packages/playground/src/components/dapp-container/dapp-container.tsx

[dapp-high-roller] [playground] [playground-server] Repairs High Roller

---

packages/dapp-tic-tac-toe/src/App.js

[dapp-tic-tac-toe] Requests appInstance as soon as CF components are connected

---

packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/machine/src/models/state-channel.ts

Winning keys must be 0th child key of extended key node address

[high roller] Fix high roller player addrs

---

packages/tic-tac-toe-bot/src/utils.ts

This brings the TTT bot up to date with the recent PG(-server) refactor that modified multisig creation.

[ticTacToeBot] Use updated multisig deployer in TTT bot

---

packages/dapp-tic-tac-toe/src/App.js

Rename Alice/Bob to Opponent/You in TTT

[dapp-tic-tac-toe] Rename Alice/Bob to Opponent/You in TTT

---

packages/machine/package.json
packages/node/package.json
yarn.lock

Forgot to bump version in https://github.com/counterfactual/monorepo/pull/1029

[machine] Bump version

---

packages/playground/src/components/account/account-eth-form/account-eth-form.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx

[playground} Fixes validation for null deposit/withdrawals

---

packages/node/src/methods/state-channel/deposit/operation.ts

Despite by best attempts in a very small # of cases sometimes the nonce is still too low. This seems to get the last remaining cases where this happens. Better solution can come later.

[node] Retry 3x deposit if unknown error

---

packages/dapp-tic-tac-toe/src/Game.jsx

It's still called by both people but now its called in a tie too

[ttt] Fix TTT logic for tying so uninstall is called

---

packages/playground/src/components/app-home/app-home/app-home.tsx

[pg] More copy on home page

---

packages/playground/src/components/dapp-container/dapp-container.tsx

Naive but functional technique for updating balances every install and uninstall

[pg] Update balances on state channel update

---

packages/playground-server/.env.local
packages/playground-server/.gitignore

It was causing nonce incrementing issues us all using the same one.

[pg-server] Remove pg-server mnemonic

---

packages/high-roller-bot/package.json
yarn.lock

[monorepo] Update yarn.lock file

---

packages/high-roller-bot/package.json
packages/playground-server/package.json

Bump to what's already published.

[playground-server] Update version number

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/components/app-root/app-root.tsx
packages/playground/src/data/account.tsx

If at any point the local balance or the counterparty's balance get below 0.01, you'll not be seeing the apps-list anymore. You'll get an error message offering you to redirect to the exchange path.

[playground] Modifies deposit condition

---

packages/playground/src/components/account/account-deposit/account-deposit.tsx
packages/playground/src/components/account/account-exchange/account-exchange.tsx

min = 0.1
max = 1
Better for hub collateralization

[pg] Set UI min and max deposit amounts

---

packages/high-roller-bot/package.json
packages/node/package.json
packages/node/src/services.ts
packages/playground-server/package.json
packages/playground-server/src/node.ts
packages/playground/package.json
packages/tic-tac-toe-bot/package.json

Slightly more descriptive logging.

[node][playground-server] Better logging

---

packages/playground/src/components/app-home/apps-list-item/apps-list-item.tsx

- Don't think we need it anymore
- Was showing on mobile

[pg] Remove collateralization widget dialog

---

packages/high-roller-bot/src/utils.ts
packages/tic-tac-toe-bot/src/utils.ts

- 3x longer timeout
- throws the real invalid json error now if retry attempts reached 0
- add log

[tttbot, hrbot] Increase time-to-wait of bots for server

---

packages/high-roller-bot/package.json
packages/high-roller-bot/src/bot.ts
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/src/bot.ts

Previously the objects weren't expanded when displayed in the shell.
This exposes the contents of objects.

[bots] More descriptive logs

---

packages/node/package.json

[node] Remove dependency

---

packages/machine/src/models/state-channel.ts
packages/node/src/store.ts

- To ensure that `getChannelByCounterparty` will return the most recently created one if there are dupes for some reason

[machine, node] Add createdAt property to StateChannel

---

packages/playground/src/components/app-home/app-home/app-home.tsx

Updates the wallet requirement message to be less confusing and more friendly.

[playground] Update wallet message

---

packages/playground/src/components/app-home/app-home/app-home.tsx

Fixes broken link to GH. Updates wallet message to include links to wallets.

[playground] Update links

---

greenkeeper.json

Stencil manages this dependency

Ignore workbox-build in greenkeeper

---

packages/contracts/contracts/test-fixtures/ResolveToPay5WeiApp.sol
packages/machine/src/types.ts
packages/machine/test/integration/message-router.ts
packages/machine/test/integration/mininode.ts
packages/machine/test/integration/protocols.spec.ts

This PR re-implements a test harness for the machine that creates instruction executors and runs protocols between them.

[machine] test harness

---

packages/playground-server/.gitignore
packages/playground-server/README.md

Clarifies the prerequisites needed to run the playground server.
https://github.com/counterfactual/monorepo/issues/1137

[playground-server] Update README

---

packages/playground-server/Dockerfile
packages/playground-server/database/schema/playground_db.sql
packages/playground-server/docker-compose.yml

Adds persistence to the DB when its spun up in a Docker container.

[playground-server] Add postgres db on playground start part 2

---

packages/playground/README.md

See the [rendered version](https://github.com/counterfactual/monorepo/blob/be9b5deae6708e2e1abd9429acef60a18f5ba89a/packages/playground/README.md).
#1188

[playground] Adds a better README for the Playground

---

packages/contracts/contracts/proxies/Proxy.sol
packages/contracts/contracts/proxies/ProxyFactory.sol
packages/contracts/contracts/test-fixtures/Echo.sol
packages/contracts/test/create2.spec.ts
packages/machine/test/integration/install-then-set-state.spec.ts
packages/machine/truffle-config.js

Added a ProxyFactory with create2.

[contracts] Add ProxyFactory with CREATE2 functionality

---

packages/dapp-high-roller/src/data/types.ts
packages/machine/src/protocol/withdraw-eth.ts
packages/machine/test/integration/protocols.spec.ts
packages/machine/test/integration/set-state.spec.ts
packages/machine/test/integration/setup-then-set-state.spec.ts
packages/machine/test/integration/virtual-app-set-state-commitment.spec.ts
packages/machine/test/mocks.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/methods/state-channel/withdraw/controller.ts
packages/node/src/network-configuration.ts
packages/node/test/integration/utils.ts
packages/node/test/node-test-environment.jest.js
packages/playground-server/test/node-test-environment.jest.js
packages/tic-tac-toe-bot/test/node-test-environment.jest.js
packages/types/src/index.ts
packages/types/src/node.ts

[monorepo] rename ETHBalanceRefund -> ETHBalanceRefundApp

---

packages/playground/src/components/app-home/app-home/app-home.scss
packages/playground/src/components/app-home/app-home/app-home.tsx
packages/playground/src/index.html

[pg] Remove Drift

---

packages/contracts/contracts/libs/LibStaticCall.sol

[contracts] delete staticcall_as_TransferDetails

---

packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/data/game-types.ts

[high-roller] delete playerNames

---

packages/contracts/waffle.js

https://github.com/counterfactual/monorepo/pull/1389/files#diff-7f01a9638af514ac70500f0b99822ed8L16 disables solc in CI but also disables it on my laptop; this PR enables it on my laptop but keeps it disabled in CI

[monorepo] enable native solc on my laptop

---

packages/node/test/integration/take-action.spec.ts
packages/node/test/integration/tic-tac-toe.ts
packages/node/test/integration/uninstall.spec.ts
packages/node/test/integration/utils.ts

This refactors the uninstall test to be more clean and legible.

[node] Refactor uninstall test

---

packages/node/src/events/channel-created/controller.ts
packages/node/src/events/protocol-message/controller.ts
packages/node/src/machine/index.ts
packages/node/src/methods/app-instance/get-all/operation.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/app-instance/propose-install-virtual/operation.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/uninstall/operation.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/errors.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/protocol/utils/get-channel-from-counterparty.ts
packages/node/src/store.ts
packages/node/src/utils.ts
packages/node/test/contract-deployments.jest.ts
packages/node/test/integration/utils.ts
packages/node/test/machine/integration/mininode.ts
packages/node/test/machine/unit/ethereum/eth-virtual-app-agreement-commitment.spec.ts
packages/node/test/node-test-environment.jest.js
packages/node/test/unit/install.spec.ts
packages/node/test/unit/utils.ts

This refactors some imports that were stale from the machine migration.

[node] Refactor imports

---

package.json

Remove nohoist of stencil. Fixes #1178.

---

packages/node/src/methods/errors.ts
packages/node/src/services.ts
packages/node/src/store.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/node-store.spec.ts

[node] throw error on null values

---

packages/node/src/machine/instruction-executor.ts
packages/node/src/machine/types.ts
packages/node/src/node.ts

Fixes #1252.
Fun fact, UUID v1 is meant for uniqueness but v4 is for randomness.

[node] Add uuid to protocol message object per handshake

---

packages/specs/source/06-update-protocol.md

fixes #1410, adds basic references to interpreters per #1487

[specs] fix definition of computeAppChallengeHash

---

packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/store.ts
packages/node/test/integration/cant-uninstall-free-balance.spec.ts

This is needed to progress https://github.com/counterfactual/monorepo/pull/1495 in updating the state of the FreeBalance AppInstance.

[node] Add mapping for appInstanceId of ETH Free Balance

---

packages/specs/source/peer-protocol.md
packages/specs/source/protocols/install-virtual-app.md
packages/specs/source/protocols/setup.md

- remove outdated information
- remove references to Alice/Bob
- add new preamble

[specs] update protocols.md

---

packages/specs/source/adjudication-layer.md
packages/specs/source/app-definition.md

This PR updates the "app definition" and "adjudication layer" files to reflect the interpreters design.

[specs] update adjudication layer for interpreters

---

packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MAppCaller.sol
packages/contracts/contracts/mixins/MixinProgressChallenge.sol
packages/contracts/contracts/mixins/MixinSetResolution.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/test/eth-virtual-app-agreement.spec.ts
packages/contracts/test/utils/index.ts
packages/node/src/ethereum/utils/encodings.ts
packages/node/src/models/app-instance.ts
packages/node/test/machine/unit/ethereum/eth-virtual-app-agreement-commitment.spec.ts
packages/node/test/machine/unit/ethereum/install-commitment.spec.ts
packages/node/test/machine/unit/ethereum/set-state-commitment.spec.ts
packages/node/test/machine/unit/ethereum/uninstall-commitment.spec.ts
packages/node/test/machine/unit/ethereum/virtual-app-set-state-commitment.spec.ts
packages/specs/source/adjudication-layer.md
packages/specs/source/protocols/update.md
packages/types/src/app-instance.ts

Addresses https://github.com/counterfactual/monorepo/issues/1520

[contracts] Rename appDefinitionAddress to appDefinition

---

packages/dapp-high-roller/package.json
packages/playground/package.json
yarn.lock

We encounter this issue when upgrading to 0.18.1.
https://github.com/ionic-team/stencil/issues/1464

Fix @stencil/core to 0.18.1-0

---

packages/apps/README.md
packages/contracts/README.md

Clarifies the address that needs to be funded to deploy the contracts.

[contracts, apps] Update deployment instructions

---

packages/node/package.json
yarn.lock

This breaks auth on prod site. The new update seems to be buggy.

Revert "Update dependency firebase to v6.0.4"

---

.circleci/images/build/Dockerfile

Previous PR #1555 added a Dockerfile that did not build

Fix Dockerfile so it builds correctly

---

packages/contracts/contracts/libs/LibStateChannelApp.sol
packages/contracts/contracts/mixins/MixinCancelChallenge.sol
packages/contracts/contracts/mixins/MixinChallengeRegistryCore.sol
packages/contracts/contracts/mixins/MixinRespondToChallenge.sol
packages/contracts/contracts/mixins/MixinSetOutcome.sol
packages/contracts/contracts/mixins/MixinSetState.sol
packages/contracts/contracts/mixins/MixinSetStateWithAction.sol
packages/contracts/contracts/mixins/MixinVirtualAppSetState.sol
packages/specs/source/adjudication-layer.md

Seems like a more explicit and descriptive name for this variable

Rename AppStatus to ChallengeStatus

---

packages/specs/source/channel-networks.md
packages/specs/source/index.rst

Gives a high-level overview of the current virtual app mechanism. Briefly explains the design goals, limitations and roadmap. fixes #1409

[specs] add channel networks

---

.circleci/images/build/Dockerfile

Hard code nodejs version in Dockerfile to 10.15.3

---

packages/firebase-server/package.json
packages/node/package.json

Remove @firebase/util

---

packages/cf.js/API_REFERENCE.md
packages/dapp-tic-tac-toe/src/MockNodeProvider.js
packages/dapp-tic-tac-toe/src/Wager.jsx

This was missed in the Interpreters #1263 PR

Remove address[2] players from TicTacToeApp data structure

---

packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/high-roller-bot/src/bot.ts

Remove address[2] playerAddrs from client HighRollerApp data structure

---

packages/apps/contracts/EthUnidirectionalPaymentApp.sol

This gives a Solidity linting warning

Move external method atop internal methods in one file

---

packages/node/src/protocol/install.ts

Add better error messages in install protocol

---

packages/apps/contracts/ETHUnidirectionalTransferApp.sol
packages/apps/migrations/2_deploy_contracts.js
packages/apps/networks/42.json
packages/apps/test/eth-transfer-app.spec.ts

Since we added the finalize mechanism to the state, the outcome was wrongly returned, since it only expected encoded `transfer` data.

[apps] Unidirectional transfer app fix outcome

---

package.json
packages/cf-wallet.js/package.json
packages/high-roller-bot/package.json
packages/high-roller-bot/yarn.lock
packages/node/package.json
packages/playground-server/package.json
packages/playground-server/yarn.lock
packages/playground/package.json
packages/tic-tac-toe-bot/package.json
packages/tic-tac-toe-bot/yarn.lock
yarn.lock

Also updates @counterfactual/node to 0.4.25

Fix ethers to 4.0.29

---

packages/apps/contracts/HighRollerApp.sol
packages/apps/contracts/NimApp.sol
packages/apps/contracts/TicTacToeApp.sol
packages/apps/test/eth-transfer-app.spec.ts
packages/apps/test/high-roller-app.spec.ts
packages/cf-wallet.js/src/app-instance.ts
packages/cf.js/src/app-instance.ts
packages/dapp-high-roller/src/components/app-game-status/app-game-status.tsx
packages/dapp-high-roller/src/components/app-game/app-game.tsx
packages/dapp-high-roller/src/components/app-provider/app-provider.tsx
packages/dapp-high-roller/src/components/app-root/app-root.tsx
packages/dapp-high-roller/src/components/app-wager/app-wager.tsx
packages/dapp-high-roller/src/data/game-types.ts
packages/high-roller-bot/src/bot.ts
packages/node/src/models/app-instance.ts
packages/types/src/data-types.ts

Had to do some big changes to the `HighRoller` contract cc: @Alonski 
Does not handle the ETHUnidirectional app @rhlsthrm wrote, yet.
Have not been able to test Playground, for some reason the `playground:matchmakeWith` flag isn't working for me locally and I haven't tried with bots, yet. Also I did not update the bot code for HR yet.

Adds turnNum to all existing apps

---

packages/apps/package.json
packages/contracts/networks/3.json
packages/contracts/networks/4.json
packages/contracts/networks/42.json
packages/contracts/package.json
packages/high-roller-bot/package.json
packages/node/package.json
packages/playground-server/package.json
packages/playground/package.json
packages/tic-tac-toe-bot/package.json

This deploys updated contracts and updates the package versions of all the upstream dependents of the updated contracts.

[contracts] Contract deployment after update

---

package.json

https://github.com/browserslist/browserslist/issues/382#issuecomment-503406612

Patch a browserlist package issue

---

package.json
packages/dapp-high-roller/package.json
packages/firebase-client/package.json
packages/playground/package.json
renovate.json
yarn.lock

Handling warnings and removing unnecessary code

Some yarn package cleanup

---

packages/node/src/protocol/utils/get-outcome-increments.ts

support multiple outcomes for uninstalling ETHTransfer outcomes

---

packages/cf.js/API_REFERENCE.md
packages/high-roller-bot/package.json
packages/node/package.json
packages/playground-server/package.json
packages/playground/package.json
packages/tic-tac-toe-bot/package.json

Publishes new version to expose #1719 and adds the necessary documentation reflecting the new method.

[node] Update node version

---

packages/apps/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/chain/package.json
packages/contracts/package.json
packages/firebase-client/package.json
packages/high-roller-bot/package.json
packages/node-provider/package.json
packages/node/package.json
packages/playground-server/package.json
packages/playground/package.json
packages/postgresql-node-connector/package.json
packages/tic-tac-toe-bot/package.json
packages/types/package.json

[types] Up version

---

packages/contracts/contracts/test-fixtures/AppWithAction.sol
packages/contracts/test/challenge-registry-dispute.spec.ts
packages/node/test/machine/integration/protocols.spec.ts

Noticed it was still using dynamic turn taking.

Make AppWithAction use correct turn taking mechanic

---

packages/node/src/events/protocol-message/controller.ts

Observed this discrepancy on playground-staging.counterfactual.com

Use router instead of outgoing for protocolMessageEventController

---

packages/types/src/node.ts

This duplicate key was introduced in #1772

[types] remove duplicate keys

---

packages/node/README.md

These were removed in #1670 but they were not replaced in that PR

[node] add Node Protocol docs

---

packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/models/free-balance.ts
packages/node/src/models/state-channel.ts
packages/node/test/integration/utils.ts
packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/set-state.spec.ts
packages/node/test/machine/integration/setup-then-set-state.spec.ts
packages/node/test/machine/integration/two-party-virtual-eth-as-lump-commitment.spec.ts
packages/node/test/machine/integration/virtual-app-set-state-commitment.spec.ts
packages/node/test/machine/unit/models/state-channel/install.spec.ts
packages/node/test/machine/unit/models/state-channel/setup-channel.spec.ts
packages/node/test/machine/unit/models/state-channel/uninstall-app.spec.ts
packages/simple-hub-server/test/contract-deployments.jest.ts
packages/simple-hub-server/test/global-setup.jest.ts

- rename `getETHFreeBalance`
- rename `createFundedFreeBalance`
- rename `configureNetworkContext` in simple-hub-server

[monorepo] renames

---

packages/apps/contracts/SimpleTwoPartySwapApp.sol
packages/apps/test/simple-swap-app.spec.ts
packages/contracts/.soliumignore
packages/contracts/contracts/interpreters/SwapInterpreter.sol
packages/contracts/contracts/libs/LibOutcome.sol
packages/contracts/test/swap-interpreter.spec.ts
packages/tic-tac-toe-bot/package.json

This is effectively the same change set as https://github.com/counterfactual/monorepo/pull/1796 but with the noise of the ERC20 commits removed as that branch was a spike.

[apps] Simple swap app, "rebased"

---

packages/node/src/message-handling/handle-node-message.ts
packages/node/src/methods/app-instance/install-virtual/controller.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/app-instance/propose-install-virtual/operation.ts
packages/node/src/methods/app-instance/propose-install/operation.ts
packages/node/src/methods/app-instance/reject-install-virtual/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/proposed-app-instance/get/controller.ts
packages/node/src/models/index.ts
packages/node/src/models/proposed-app-instance-info.ts
packages/node/src/store.ts
packages/node/test/integration/install.spec.ts
packages/node/test/integration/reject-install.spec.ts
packages/node/test/integration/utils.ts
packages/node/test/machine/unit/ethereum/conditional-transaction-commitment.spec.ts
packages/node/test/machine/unit/ethereum/set-state-commitment.spec.ts
packages/node/test/machine/unit/models/state-channel/install.spec.ts
packages/node/test/machine/unit/models/state-channel/set-state.spec.ts
packages/node/test/machine/unit/models/state-channel/uninstall-app.spec.ts
packages/node/test/unit/install.spec.ts
packages/node/test/unit/utils.ts

Step 1 of removing the notion of `AppInstanceInfo`

Rename ProposedAppInstanceInfo to AppInstanceProposal

---

packages/playground/src/components/dapp-container/dapp-container.tsx
packages/playground/src/data/counterfactual.ts

> Yay! You're creating a new PR. Keep in mind these guidelines:
>
> - Set the title following this convention:
>
>   [feature-group][change-summary]
>
>   where:
>
>   - `feature-group` represents either a monorepo package, or other features such as "documentation" or "lint".
>   - `change-summary` is a one-sentence version of the PR description.
>
> - Tag the PR appropriately:
>   - If you're early-opening a PR in do further work on it, tag it with the "in progress" label.
>   - If it belongs to a package, use the corresponding label (i.e. _"Package: machine"_).
>   - If it updates documentation, tag it with the "documentation" label.
>   - If your work has dependencies with other contributors, tag it with the "waiting" label.
>
> Once you're good to go, delete these guidelines :) …

fix: missing router renamed to rpcRouter in PG UI

---

packages/contracts/contracts/interpreters/TwoPartyFixedOutcomeETHInterpreter.sol
packages/contracts/contracts/interpreters/TwoPartyFixedOutcomeFromVirtualAppETHInterpreter.sol

This adds some notes the interpreters specifying asset type and outcome

add notes to interpreters

---

packages/apps/migrations/2_deploy_contracts.js
packages/apps/networks/42.json

Add migration for swap app and deploy.

[apps] Add deployment for swap app

---

packages/apps/package.json
packages/chain/package.json
packages/contracts/networks/3.json
packages/contracts/networks/4.json
packages/contracts/networks/42.json
packages/contracts/package.json
packages/contracts/truffle-config.js
packages/high-roller-bot/package.json
packages/node/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

Fixes https://github.com/counterfactual/monorepo/issues/1950 and https://github.com/counterfactual/monorepo/issues/1917

[contracts] Fix contracts build dir

---

packages/node/src/models/app-instance.ts

Removes internal `json` representation

Simplify AppInstance model implementation

---

packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/test/integration/secure-deposit.spec.ts

this threw us off for a bit ngl

[node] token address passed to deposit error

---

packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/rpc-router.ts
packages/node/test/integration/cant-take-action.spec.ts
packages/node/test/integration/get-app-instance.spec.ts
packages/node/test/integration/get-state.spec.ts
packages/node/test/integration/install-virtual.spec.ts
packages/node/test/integration/install.spec.ts
packages/node/test/integration/reject-install-virtual-with-postgres.spec.ts
packages/node/test/integration/reject-install-virtual.spec.ts
packages/node/test/integration/reject-install.spec.ts
packages/node/test/integration/take-action-virtual.spec.ts
packages/node/test/integration/take-action.spec.ts
packages/node/test/integration/tic-tac-toe.ts
packages/node/test/integration/uninstall-virtual.spec.ts
packages/node/test/integration/uninstall-with-postgres.spec.ts
packages/node/test/integration/uninstall.spec.ts
packages/node/test/integration/utils.ts

Fixes most of https://github.com/counterfactual/monorepo/issues/1910

[node] Refactors some test utils and fixes some errors

---

packages/simple-hub-server/src/index.ts
packages/wallet-ui/src/App.tsx
packages/wallet-ui/src/components/account/account-context/AccountContext.tsx
packages/wallet-ui/src/store/user/user.ts

This fixes the end of the onboarding flow, in which the user wasn't being shown as logged in.
closes #1983

[Wallet-UI] Registration redirection fix

---

packages/wallet-ui/src/components/account/account-context/AccountContext.mock.json
packages/wallet-ui/src/store/user/user.spec.ts

#2023 was incorrectly merged with broken tests. This PR takes care of it.

[wallet-ui] Fixes broken tests on `master`

---

packages/cf-metamask-extension/README.md

[Rendered view here.](https://github.com/counterfactual/monorepo/blob/b066a76e882a007f97d9f7f15eb6b316bff0a65d/packages/cf-metamask-extension/README.md)
Resolves #2026.

[cf-metamask-extension] Updates usage guidelines

---

packages/high-roller-bot/package.json
packages/node/package.json
packages/node/src/message-handling/handle-protocol-message.ts
packages/playground/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

[node] Fix deserialize issue

---

packages/apps/contracts/UnidirectionalTransferApp.sol
packages/apps/networks/3.json
packages/apps/networks/4.json
packages/apps/networks/42.json
packages/apps/package.json
packages/dapp-tic-tac-toe/package.json
packages/high-roller-bot/package.json
packages/local-ganache-server/package.json
packages/node/package.json
packages/playground/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

Fix a typo in the `UnidirectionalTransferApp`.

Fix error in UnidirectionalTransferApp

---

package.json
yarn.lock

A while ago we had to add this to fix a problem in one of the dependencies but it was fixed now.

Remove some resolution files we no longer need

---

packages/wallet-ui/src/App.test.tsx
packages/wallet-ui/src/components/account/account-context/AccountContext.spec.tsx
packages/wallet-ui/src/components/account/account-context/AccountContext.tsx
packages/wallet-ui/src/store/test-utils/ethereum.mock.ts
packages/wallet-ui/src/store/user/user.mock.ts
packages/wallet-ui/src/store/user/user.spec.ts
packages/wallet-ui/src/store/user/user.ts
packages/wallet-ui/src/utils/counterfactual.spec.ts
packages/wallet-ui/src/utils/counterfactual.ts

This PR is related to [this other one](https://github.com/prototypal/metamask-extension/pull/7).
- It modifies a function so that Wallet-UI works with @Alonskis MM branch.
- It improves the login flow (it wasn't getting the balance when login in).
- It adds a better function to get the CF balance.
And finally, it also modifies the tests for everything of the above mentioned changes.

[Wallet-UI] Alonskys branch MM Integration & small fixes

---

packages/wallet-ui/src/components/form/form-input/FormInput.scss
packages/wallet-ui/src/components/form/form-input/FormInput.tsx
packages/wallet-ui/src/pages/account-deposit/AccountDeposit.tsx
packages/wallet-ui/src/pages/account-withdraw/AccountWithdraw.tsx
packages/wallet-ui/src/store/types.ts
packages/wallet-ui/src/store/wallet/wallet.mock.ts
packages/wallet-ui/src/store/wallet/wallet.spec.ts
packages/wallet-ui/src/store/wallet/wallet.ts
packages/wallet-ui/src/utils/counterfactual.ts

This PR fixes some transitions on the deposit flow, by refactoring a function, and changing the message shown to the user.
related to #1955 
closes #1981

[Wallet UI] Transition fixes & FormInput Unit selector

---

packages/high-roller-bot/package.json
packages/node/package.json
packages/playground/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

This publishes the changes in #2088 to npm

[monorepo] bump node version

---

packages/wallet-ui/README.md

[Click here to see the rendered view.](https://github.com/counterfactual/monorepo/tree/joel/wallet-ui-readme/packages/wallet-ui/README.md)
Resolves #2030.

[wallet-ui] Adds a more concise README for the package

---

packages/greenboard/README.md
packages/greenboard/tests/onboarding.spec.ts
packages/greenboard/utils/test-browser.ts

[Rendered version here](https://github.com/counterfactual/monorepo/tree/joel/greenboard-readme/packages/greenboard/README.md).
Contributes to #1907.

[greenboard] Adds documentation for using the package and creating new scenarios

---

packages/wallet-ui/README.md

Fix Metamask -> MetaMask
#2099

Fix Metamask -> MetaMask

---

packages/high-roller-bot/package.json
packages/node/package.json
packages/node/src/methods/app-instance/get-all/controller.ts
packages/node/test/integration/install.spec.ts
packages/playground/package.json
packages/simple-hub-server/package.json
packages/tic-tac-toe-bot/package.json

This fixes the false positive happening here: https://github.com/counterfactual/monorepo/blob/1ebc02dc83168865695c47d33cbbb4e345a52510/packages/node/test/integration/install.spec.ts#L67

[node] Update implementation for GetAppInstancesController controller

---

.circleci/config.yml

Checks are getting stuck with `run-tests` not returning a result. This PR attempts to fix that.

[monorepo] Fixes CI configuration

---

packages/cf.js/package.json
packages/cf.js/src/index.ts
yarn.lock

[cf.js] Allows usage of NodeProviderEthereum

---

packages/node/src/machine/types.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/state-channel/deposit/operation.ts
packages/node/src/protocol/install.ts
packages/node/test/machine/integration/protocols/test-runner.ts

[node] disable limit for refund app install

---

packages/wallet-ui/src/components/account/account-context/AccountContext.scss
packages/wallet-ui/src/components/account/account-context/AccountContext.tsx
packages/wallet-ui/src/components/widget/widget-tooltip/WidgetTooltip.scss
packages/wallet-ui/src/components/widget/widget-tooltip/WidgetTooltip.tsx

This PR gives the user feedback when the login attempt fails, previously it wouldn't show anything if it failed.
Now it shows this:
It closes #2147

[Wallet-UI] Add feedback on failed login

---

packages/firebase-client/src/index.ts
packages/firebase-server/test/integration/store.spec.ts
packages/node/src/signer.ts
packages/node/src/store.ts
packages/node/test/integration/setup.ts
packages/node/test/services/memory-store-service.ts
packages/postgresql-node-connector/src/index.ts
packages/postgresql-node-connector/test/save-load.spec.ts
packages/simple-hub-server/src/node.ts
packages/types/src/node.ts

This brings the interface in line with Firebase terminology and with how we actually treat variables with this name

[node] IStoreService: rename key to path

---

packages/node/package.json
packages/node/rollup.config.js
packages/simple-hub-server/package.json
yarn.lock

This bumps the Node along with the package using it: Simple Hub Server
#2179

Bump Node Version + Simple Hub Server

---

packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json

[monorepo] bump types version

---

e2e-prepare.sh

[greenboard] Fallbacks to $(which python2.7) if no PYTHON env var exists

---

e2e-run.sh

[greenboard] Uses node-gyp-powered sqlite3 if no sqlite3 binary is installed in the system

---

packages/node/package.json
packages/node/src/methods/app-instance/get-free-balance/controller.ts
packages/node/src/methods/errors.ts
packages/node/src/models/free-balance.ts
packages/node/test/integration/secure-deposit.spec.ts
packages/simple-hub-server/package.json

fixes: https://github.com/counterfactual/monorepo/issues/2016

[node] Return zero balance for token pre-deposit

---

packages/node/src/machine/instruction-executor.ts
packages/node/src/machine/types.ts
packages/node/src/node.ts
packages/node/src/protocol/install-virtual-app.ts
packages/node/src/protocol/install.ts
packages/node/src/protocol/setup.ts
packages/node/src/protocol/take-action.ts
packages/node/src/protocol/uninstall-virtual-app.ts
packages/node/src/protocol/uninstall.ts
packages/node/src/protocol/update.ts
packages/node/src/protocol/withdraw.ts

A process is an instance of a protocol

Rename protocolExecution to process

---

packages/specs/source/diagrams/takeaction-protocol-exchange.mmd
packages/specs/source/peer-protocol.md
packages/specs/source/protocols/install-virtual-app.md
packages/specs/source/protocols/install.md
packages/specs/source/protocols/take-action.md
packages/specs/source/protocols/uninstall-virtual-app.md
packages/specs/source/protocols/uninstall.md
packages/specs/source/protocols/update.md

- fix #1502 
- add customData
- fix some `appInstanceId`s
- add `{initiator,respondor}BalanceDecrement` to `InstallParams`

[specs] update specs

---

packages/node/test/machine/integration/install-then-set-state.spec.ts
packages/node/test/machine/integration/install-virtual.spec.ts
packages/node/test/machine/integration/setup-then-set-state.spec.ts

Adds a test to one of the integration tests for the create2 address

Ensures create2 address is correct on ganache-cli

---

packages/node-provider/src/node-provider-ethereum.ts
packages/node-provider/src/node-provider.ts
packages/node-provider/test/unit/node-provider-ethereum.spec.ts
packages/node-provider/test/unit/node-provider.spec.ts
packages/types/src/index.ts
packages/types/src/node.ts

This doesn't affect run-time behaviour (except in tests)

[node-provider] replace INodeProvider with IRpcNodeProvider

---

packages/node/package.json
packages/simple-hub-server/package.json

To release https://github.com/counterfactual/monorepo/pull/2232 in a release version

[node] Bump node version

---

packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-adjudicator-contracts/waffle.js
packages/cf-funding-protocol-contracts/package.json
packages/cf-funding-protocol-contracts/waffle.js
packages/local-ganache-server/package.json
packages/node/package.json
packages/simple-hub-server/package.json

#2224 changed some waffle flags to make ProxyFactory.json more reproducible; this PR applies the same change to all other waffle configs

[contracts] pass waffle flags

---

packages/apps/README.md
packages/apps/package.json
packages/cf-adjudicator-contracts/README.md
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/README.md
packages/cf-funding-protocol-contracts/package.json
packages/local-ganache-server/package.json
packages/node/package.json

[contracts] Fix package scripts to re-introduce build artifacts in CI

---

packages/node/test/integration/utils.ts

Makes errors from `makeVirtualProposal` show proper stack traces

Simplify test utility function

---

packages/node/src/methods/queued-execution.ts
packages/node/test/unit/queued-execution.spec.ts

Third one fails, isolating an issue.

Add tests to queueing helper function

---

packages/node/src/methods/app-instance/install-virtual/controller.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/uninstall-virtual/controller.ts
packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/controller.ts
packages/node/src/methods/queued-execution.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/withdraw-commitment/controller.ts
packages/node/src/methods/state-channel/withdraw/controller.ts

Removes complexity from controllers.

Move requestHandler.getShardedQueue to single location

---

packages/node/package.json
packages/node/src/protocol/take-action.ts

- Cleaner code
- Easier to reason about

Clean up implementation of TAKE_ACTION_PROTOCOL

---

packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/methods/app-instance/uninstall-virtual/controller.ts

Queues on the app id for uninstalling a virtual app, as well as the relevant multisig addresses

queue on app id for uninstall virtual

---

packages/node/src/protocol/uninstall.ts

Did this while working on another upcoming PR.

Improve readability of UNINSTALL_PROTOCOL

---

packages/node/src/protocol/update.ts

Did this while working on an upcoming PR.

Improve readability of UPDATE_PROTOCOL

---

packages/node/src/protocol/take-action.ts

Rename variables in take action protocol

---

packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json

[node] [types] Bump versions

---

packages/node/src/methods/app-instance/install-virtual/controller.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/propose-install-virtual/controller.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/methods/app-instance/take-action/controller.ts
packages/node/src/methods/app-instance/uninstall-virtual/controller.ts
packages/node/src/methods/app-instance/uninstall/controller.ts
packages/node/src/methods/app-instance/update-state/controller.ts
packages/node/src/methods/controller.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/methods/state-channel/deposit/controller.ts
packages/node/src/methods/state-channel/withdraw-commitment/controller.ts
packages/node/src/methods/state-channel/withdraw/controller.ts
packages/node/test/integration/get-state.spec.ts

I think this is a better name for this method.

Rename getShardKeysForQueueing to getRequiredLockNames

---

packages/node/src/protocol/uninstall.ts
packages/node/test/integration/uninstall.spec.ts

Part of ongoing work in https://github.com/counterfactual/monorepo/issues/2435

UNINSTALL_FINISHED event

---

packages/node/package.json
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/methods/app-instance/propose-install/controller.ts
packages/node/src/protocol/install.ts
packages/node/test/integration/channel-creation.spec.ts
packages/node/test/integration/install.spec.ts
packages/simple-hub-server/package.json

Initiator sends message to counterparty in install to emit event once the protocol has finished for all involved parties.
#2435

[node] Implements emission of INSTALL_FINISHED event across parties

---

packages/node/package.json
packages/node/src/node.ts
packages/node/test/integration/channel-creation.spec.ts
packages/node/test/integration/uninstall.spec.ts
packages/simple-hub-server/package.json

Minor fix to stop potential race

Flip event emission order

---

packages/cf-funding-protocol-contracts/networks/1.json
packages/cf-funding-protocol-contracts/package.json
packages/local-ganache-server/package.json
packages/node/package.json

Updated for mainnet using `manual-deploy.js`.

Update proxy address

---

package.json
packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/firebase-server/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json
packages/typescript-typings/package.json

Allows for different node and yarn engines for downstream consumers of packages.
#2394

[all] relax engines preferences

---

packages/node/src/message-handling/handle-node-message.ts
packages/node/src/message-handling/handle-protocol-message.ts
packages/node/src/methods/app-instance/install-virtual/operation.ts
packages/node/src/methods/app-instance/install/controller.ts
packages/node/src/methods/app-instance/install/operation.ts
packages/node/src/methods/app-instance/propose-install/operation.ts
packages/node/src/methods/app-instance/reject-install-virtual/controller.ts
packages/node/src/methods/app-instance/reject-install/controller.ts
packages/node/src/models/state-channel.ts
packages/node/src/store.ts
packages/node/test/unit/install.spec.ts

The store should just be a blob you can save to disk and retrieve when necessary and in-memory during node operation. This begins that work.

Remove proposals from Store DB

---

packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf-wallet.js/src/provider.ts
packages/cf-wallet.js/test/provider.spec.ts
packages/cf.js/package.json
packages/firebase-client/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/docs/source/api.md
packages/node/package.json
packages/node/src/methods/index.ts
packages/node/src/methods/state-channel/create/controller.ts
packages/node/src/methods/state-channel/deploy-state-deposit-holder/controller.ts
packages/node/src/methods/state-channel/withdraw/controller.ts
packages/node/test/integration/deploy-state-deposit-holder.spec.ts
packages/node/test/integration/secure-withdraw.spec.ts
packages/node/test/integration/utils.ts
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/simple-hub-server/src/node.ts
packages/types/package.json
packages/types/src/node.ts

[node] Deploy multisig on withdraw

---

packages/specs/source/adjudication-layer.md

[documentation]Add a missing space

---

package.json

Support all Node 10 and Node 12 versions.

[all] Node version

---

packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/firebase-server/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json
packages/typescript-typings/package.json

Last update didn't update individual packages or bump versions.

[all] Update node engines

---

packages/node/src/machine/enums.ts
packages/node/src/methods/app-instance/propose-install/operation.ts
packages/node/src/models/app-instance-proposal.ts
packages/node/src/models/free-balance.ts
packages/node/src/protocol/propose.ts
packages/node/test/integration/utils.ts
packages/node/test/unit/utils.ts
packages/types/src/data-types.ts

Ensures proposals only use `string`

Remove BigNumberish proposal fields

---

packages/apps/package.json
packages/cf-adjudicator-contracts/package.json
packages/cf-funding-protocol-contracts/package.json
packages/cf-wallet.js/package.json
packages/cf.js/package.json
packages/firebase-client/package.json
packages/local-ganache-server/package.json
packages/node-provider/package.json
packages/node/package.json
packages/postgresql-node-connector/package.json
packages/simple-hub-server/package.json
packages/types/package.json

[all] Update and bump versions for node, types, and contracts

---

packages/node/package.json
packages/node/src/engine/withdraw.ts
packages/node/test/integration/secure-withdraw.spec.ts

free balance doesn't properly decrement for responders channel in withdraw protocol

[node] free balance problems in withdrawal commitment
